In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Set visualization style for all plots
sns.set_theme(style="whitegrid", palette="muted")

# Define the directory where your 17 CSV files are stored
DATA_DIR = '.' 

# ---------------------------------------------------------
# 1. DATA LOADING
# ---------------------------------------------------------
def load_data(filename):
    """Safely load a CSV file into a pandas DataFrame."""
    file_path = os.path.join(DATA_DIR, filename)
    try:
        print(f"Loading {filename}...")
        return pd.read_csv(file_path, low_memory=False)
    except FileNotFoundError:
        print(f"  -> Warning: {filename} not found. Skipping.")
        return None

print("=== PART 1: LOADING DATASETS ===")
datasets = {
    's2_shift_cov_lap': load_data('results_S2_model_shift_mean_cov_lap.csv'),
    's3_fix_na_lap': load_data('results_S3_model_fix_mean_lap.csv'),
    's3_fix_na_na': load_data('results_S3_model_fix_mean.csv'),
    's5_shift_global_lap': load_data('results_S5_model_shift_mean_paper_lap.csv'),
    's5_shift_global_na': load_data('results_S5_model_shift_mean_paper.csv')
}

=== PART 1: LOADING DATASETS ===
Loading results_S2_model_shift_mean_cov_lap.csv...
Loading results_S3_model_fix_mean_lap.csv...
Loading results_S3_model_fix_mean.csv...
Loading results_S5_model_shift_mean_paper_lap.csv...
Loading results_S5_model_shift_mean_paper.csv...

In [3]:
datasets["s2_shift_cov_lap"] # Display the first few rows of one dataset to verify loading

,Parameter,True_Value,Estimate,2.5%,97.5%,R_hat,ESS,Rbias,MSE,Coverage
0,theta1,2.30,-2.432550,-3.026780,-1.913780,1.000370,6664.2000,-2.057630,22.397030,0
1,theta2,2.60,-3.171190,-4.372010,-2.292240,1.012930,851.1180,-2.219688,33.306634,0
2,theta3,2.90,-2.397000,-3.104000,-1.787650,1.002450,4566.2700,-1.826552,28.058209,0
3,theta4[1],-4.00,-3.527760,-4.012370,-3.065250,0.999983,9262.1900,-0.118060,0.223011,1
4,theta4[2],-1.00,-0.575080,-0.973934,-0.180074,0.999709,10454.0000,-0.424920,0.180557,0
5,theta4[3],2.70,3.004390,2.564620,3.460900,1.000140,9762.2000,0.112737,0.092653,1
6,theta5[1],-7.50,-8.014750,-9.496970,-6.800710,1.001140,4403.1100,0.068633,0.264968,1
7,theta5[2],-2.50,-2.709390,-3.597550,-1.904120,1.000330,7193.1300,0.083756,0.043844,1
8,theta5[3],2.60,2.711130,1.891630,3.583830,1.000020,8764.8300,0.042742,0.012350,1
9,theta6[1],-5.50,-5.697880,-6.443280,-5.005600,1.000440,9207.4700,0.035978,0.039156,1
10,theta6[2],-2.70,-2.739390,-3.354120,-2.159400,1.000380,10809.0000,0.014589,0.001552,1
11,theta6[3],2.50,2.489360,1.910800,3.076750,1.000500,11248.8000,-0.004256,0.000113,1
12,theta7[1],-4.30,-4.290580,-4.660130,-3.934160,1.000270,9685.1500,-0.002191,0.000089,1
13,theta7[2],-1.00,-1.118830,-1.382150,-0.864850,1.000590,8961.1700,0.118830,0.014121,1
14,theta7[3],1.40,1.366010,1.109590,1.626140,0.999958,9638.2100,-0.024279,0.001155,1
15,lambda[1],1.20,1.286210,0.838811,1.784540,1.000920,6481.4900,0.071842,0.007432,1
16,lambda[2],4.00,4.582260,3.352250,6.352940,1.010110,1881.3700,0.145565,0.339027,1
17,lambda[3],4.10,3.041750,2.302640,3.937690,1.001930,3736.4700,-0.258110,1.119893,0
18,lambda[4],3.10,2.999870,2.622040,3.408590,1.003770,4349.3300,-0.032300,0.010026,1
19,lambda[5],5.20,5.604850,4.662020,6.765990,1.005120,2349.1300,0.077856,0.163904,1
20,lambda[6],3.00,3.088900,2.653030,3.582370,1.003790,3759.6900,0.029633,0.007903,1
21,lambda[7],1.70,1.909150,1.680400,2.148150,1.001710,6192.7600,0.123029,0.043744,1
22,"beta[1,1]",0.30,-0.048711,-0.416363,0.316057,0.999995,11177.9000,-1.162370,0.121599,1
23,"beta[1,2]",0.50,-0.675343,-0.885692,-0.469439,1.000100,9332.3400,-2.350686,1.381431,0
24,"beta[2,1]",0.10,0.103768,-0.397051,0.611242,1.001260,10964.7000,0.037680,0.000014,1
25,"beta[2,2]",0.20,-0.456852,-0.753781,-0.198376,1.002860,4672.5400,-3.284260,0.431455,0
26,"beta[3,1]",-0.10,0.623025,0.214140,1.061710,1.000690,11240.7000,-7.230250,0.522765,0
27,"beta[3,2]",0.20,-0.266918,-0.494210,-0.056451,1.000760,10328.3000,-2.334590,0.218012,0
28,"beta[4,1]",-0.20,0.375385,0.117766,0.630575,1.001280,12354.5000,-2.876925,0.331068,0
29,"beta[4,2]",0.40,-0.472330,-0.607696,-0.340047,0.999920,11196.2000,-2.180825,0.760960,0
30,"beta[5,1]",0.30,-0.370208,-0.766690,0.012390,1.000160,11444.5000,-2.234027,0.449179,0
31,"beta[5,2]",-0.30,0.202678,0.012011,0.398639,1.000190,10886.4000,-1.675593,0.252685,0
32,"beta[6,1]",-0.10,0.138836,-0.145711,0.424505,0.999975,11480.9000,-2.388360,0.057043,1
33,"beta[6,2]",-0.20,0.148905,0.007269,0.294578,1.000970,11324.9000,-1.744525,0.121735,0
34,"beta[7,1]",-0.20,0.129728,-0.081992,0.333256,1.000960,12035.9000,-1.648640,0.108721,0
35,"beta[7,2]",-0.10,0.021240,-0.086689,0.130422,1.000770,11378.6000,-1.212398,0.014699,0
36,sigma_bk[1],3.70,3.764970,3.159010,4.469690,1.001430,3124.7000,0.017559,0.004221,1
37,sigma_bk[2],3.40,3.911640,2.825060,5.372850,1.028350,324.0200,0.150482,0.261775,1
38,sigma_bk[3],4.80,3.893150,3.144560,4.808750,1.012370,1055.3700,-0.188927,0.822377,1
39,sigma_bk[4],3.10,3.268290,2.900470,3.673080,1.002390,3700.5300,0.054287,0.028322,1
40,sigma_bk[5],6.10,6.488870,5.498960,7.685720,1.002920,2766.9800,0.063749,0.151220,1
41,sigma_bk[6],5.10,5.299400,4.698190,5.972190,1.000960,4203.3700,0.039098,0.039760,1
42,sigma_bk[7],1.70,1.614400,1.386390,1.843880,1.004560,2228.1100,-0.050353,0.007327,1
43,rho,0.60,0.620466,0.518429,0.719387,1.006220,1324.6200,0.034110,0.000419,1
44,"Gamma[1,1]",0.18,0.161321,0.084213,0.281925,1.070190,95.5899,-0.103772,0.000349,1
45,"Gamma[1,2]",-0.07,-0.047172,-0.149457,0.026889,1.036700,179.5660,-0.326109,0.000521,1
46,"Gamma[2,1]",0.10,0.087706,0.014261,0.166570,1.003700,2222.3100,-0.122941,0.000151,1
47,"Gamma[2,2]",0.15,0.143163,0.070862,0.214066,1.006810,2607.9600,-0.045580,0.000047,1

In [4]:
datasets["s3_fix_na_lap"]

,Parameter,True_Value,Estimate,2.5%,97.5%,R_hat,ESS,Rbias,MSE,Coverage
0,theta1,2.30,-1.478710,-1.952960,-1.040520,1.000280,7398.710,-1.642917,14.278649,0
1,theta2,2.60,0.296946,-0.853474,1.662470,1.001630,6042.630,-0.885790,5.304058,0
2,theta3,2.90,-0.628147,-2.003370,0.511789,1.002570,5462.660,-1.216602,12.447821,0
3,theta4[1],-4.00,-1.294870,-1.734900,-0.860695,1.000960,5635.010,-0.676283,7.317728,0
4,theta4[2],-1.00,1.418610,0.972412,1.875210,1.001210,5844.980,-2.418610,5.849674,0
5,theta4[3],2.70,4.835970,4.287830,5.420080,1.000790,6381.600,0.791100,4.562368,0
6,theta5[1],-7.50,-3.678050,-4.642820,-2.805690,1.000700,5238.560,-0.509593,14.607302,0
7,theta5[2],-2.50,1.241530,0.470458,2.070370,1.001770,5016.180,-1.496612,13.999047,0
8,theta5[3],2.60,6.083560,5.026600,7.340850,1.003420,3463.930,1.339831,12.135190,0
9,theta6[1],-5.50,-3.470090,-4.190420,-2.802470,1.000270,7201.490,-0.369075,4.120535,0
10,theta6[2],-2.70,-0.298816,-0.942555,0.331927,1.000550,6641.080,-0.889327,5.765685,0
11,theta6[3],2.50,5.026310,4.271270,5.828950,1.000600,5979.070,1.010524,6.382242,0
12,theta7[1],-4.30,-3.012310,-3.351320,-2.682300,1.000520,6211.000,-0.299463,1.658146,0
13,theta7[2],-1.00,0.321693,0.035220,0.608484,1.000750,5609.410,-1.321693,1.746872,0
14,theta7[3],1.40,2.671330,2.349280,3.001410,1.000920,5667.330,0.908093,1.616280,0
15,lambda[1],1.20,1.584050,1.236830,1.980310,1.000810,5964.500,0.320042,0.147494,0
16,lambda[2],4.00,11.740300,6.535560,23.166100,1.009230,1288.950,1.935075,59.912244,0
17,lambda[3],4.10,9.460880,5.782800,17.265400,1.006920,1555.680,1.307532,28.739034,0
18,lambda[4],3.10,3.464980,3.070660,3.903050,1.001370,4376.730,0.117735,0.133210,1
19,lambda[5],5.20,6.163490,5.158950,7.422410,1.005730,1887.210,0.185287,0.928313,1
20,lambda[6],3.00,4.055460,3.520690,4.662520,1.002090,3655.700,0.351820,1.113996,0
21,lambda[7],1.70,2.301800,2.057450,2.559560,1.001130,4612.800,0.354000,0.362163,0
22,"beta[1,1]",0.30,-0.237668,-0.583645,0.103592,0.999984,11115.700,-1.792227,0.289087,0
23,"beta[1,2]",0.50,-0.436249,-0.623745,-0.253361,1.000480,10925.500,-1.872498,0.876562,0
24,"beta[2,1]",0.10,-0.870916,-2.282920,0.118976,1.001920,5624.070,-9.709160,0.942678,1
25,"beta[2,2]",0.20,-0.473216,-1.238430,0.059103,1.000980,5207.020,-3.366080,0.453220,0
26,"beta[3,1]",-0.10,1.071090,0.157343,2.387070,1.001980,5282.410,-11.710900,1.371452,0
27,"beta[3,2]",0.20,-0.015210,-0.532983,0.496828,1.000400,10716.900,-1.076052,0.046316,1
28,"beta[4,1]",-0.20,0.170269,-0.093905,0.433440,1.000070,12500.400,-1.851345,0.137099,0
29,"beta[4,2]",0.40,-0.436169,-0.570320,-0.304155,1.000900,12593.700,-2.090422,0.699179,0
30,"beta[5,1]",0.30,-0.297531,-0.682285,0.079041,1.000240,12397.300,-1.991770,0.357043,0
31,"beta[5,2]",-0.30,0.247275,0.056888,0.446500,1.000600,9612.300,-1.824250,0.299510,0
32,"beta[6,1]",-0.10,0.041460,-0.266545,0.340730,1.000980,12642.500,-1.414605,0.020011,1
33,"beta[6,2]",-0.20,0.117026,-0.034628,0.267798,1.000250,11818.500,-1.585130,0.100505,0
34,"beta[7,1]",-0.20,0.152159,-0.059361,0.365557,1.001110,12831.600,-1.760795,0.124016,0
35,"beta[7,2]",-0.10,0.070143,-0.038988,0.179013,1.000220,11518.200,-1.701434,0.028949,0
36,sigma_bk[1],3.70,3.565410,3.025330,4.197000,1.001440,3558.670,-0.036376,0.018114,1
37,sigma_bk[2],3.40,4.442170,1.626710,8.932600,1.015560,614.439,0.306521,1.086118,1
38,sigma_bk[3],4.80,8.230160,5.113270,14.767200,1.005970,1755.120,0.714617,11.765998,0
39,sigma_bk[4],3.10,3.002040,2.641520,3.389480,1.000880,3891.650,-0.031600,0.009596,1
40,sigma_bk[5],6.10,5.908900,5.005870,7.035490,1.004080,2264.280,-0.031328,0.036519,1
41,sigma_bk[6],5.10,5.658090,4.985760,6.398610,1.000900,4938.460,0.109429,0.311464,1
42,sigma_bk[7],1.70,1.611860,1.381590,1.853890,1.002040,2437.170,-0.051847,0.007769,1
43,rho,0.60,-0.053513,-0.137899,0.029175,1.000880,6647.530,-1.089188,0.427079,0
44,"Gamma[1,1]",0.18,0.216356,0.170942,0.267716,1.006500,1393.350,0.201978,0.001322,1
45,"Gamma[1,2]",-0.07,-0.166734,-0.208660,-0.124016,1.000840,5583.640,1.381914,0.009357,0
46,"Gamma[2,1]",0.10,0.126202,0.077348,0.174865,1.002790,4383.250,0.262020,0.000687,1
47,"Gamma[2,2]",0.15,0.160972,0.131943,0.193084,1.005800,1750.630,0.073147,0.000120,1

In [5]:
datasets["s3_fix_na_na"]

,Parameter,True_Value,Estimate,2.5%,97.5%,R_hat,ESS,Rbias,MSE,Coverage
0,theta1,2.30,-1.475760,-1.958370,-1.037660,1.00010,7890.26,-1.641635,14.256364,0
1,theta2,2.60,0.312047,-0.885626,1.639270,1.00140,5403.47,-0.879982,5.234729,0
2,theta3,2.90,-0.606928,-1.936180,0.527265,1.00111,5437.87,-1.209286,12.298544,0
3,theta4[1],-4.00,-1.301050,-1.749710,-0.853032,1.00014,5653.15,-0.674737,7.284331,0
4,theta4[2],-1.00,1.413880,0.962190,1.877330,1.00029,5387.58,-2.413880,5.826817,0
5,theta4[3],2.70,4.834740,4.287610,5.421720,1.00059,5413.69,0.790644,4.557115,0
6,theta5[1],-7.50,-3.698330,-4.653580,-2.837640,1.00206,5095.08,-0.506889,14.452695,0
7,theta5[2],-2.50,1.234870,0.456002,2.079230,1.00184,4359.70,-1.493948,13.949254,0
8,theta5[3],2.60,6.092590,5.021690,7.376750,1.00088,3648.22,1.343304,12.198185,0
9,theta6[1],-5.50,-3.474080,-4.182220,-2.789790,1.00090,7033.43,-0.368349,4.104352,0
10,theta6[2],-2.70,-0.301852,-0.940903,0.316937,1.00053,7118.85,-0.888203,5.751114,0
11,theta6[3],2.50,5.023300,4.278750,5.832140,1.00117,6580.35,1.009320,6.367043,0
12,theta7[1],-4.30,-3.016760,-3.353400,-2.692070,1.00105,6284.87,-0.298428,1.646705,0
13,theta7[2],-1.00,0.317442,0.032746,0.606356,1.00151,5222.22,-1.317442,1.735653,0
14,theta7[3],1.40,2.665770,2.346680,2.991070,1.00117,5722.31,0.904121,1.602174,0
15,lambda[1],1.20,1.575740,1.225960,1.974810,1.00117,5583.38,0.313117,0.141181,0
16,lambda[2],4.00,11.771300,6.549860,23.620900,1.00593,1205.32,1.942825,60.393104,0
17,lambda[3],4.10,9.423810,5.742460,17.073700,1.00430,1670.68,1.298490,28.342953,0
18,lambda[4],3.10,3.473510,3.072230,3.919770,1.00174,3543.29,0.120487,0.139510,1
19,lambda[5],5.20,6.196150,5.177580,7.428670,1.00171,2310.71,0.191567,0.992315,1
20,lambda[6],3.00,4.059840,3.527690,4.663760,1.00283,2970.34,0.353280,1.123261,0
21,lambda[7],1.70,2.303510,2.055330,2.572470,1.00164,4359.85,0.355006,0.364224,0
22,"beta[1,1]",0.30,-0.233798,-0.576062,0.101031,1.00170,13106.50,-1.779327,0.284940,0
23,"beta[1,2]",0.50,-0.435258,-0.626159,-0.246709,1.00041,11032.90,-1.870516,0.874708,0
24,"beta[2,1]",0.10,-0.868158,-2.248410,0.124330,1.00149,4556.57,-9.681580,0.937330,1
25,"beta[2,2]",0.20,-0.476475,-1.300630,0.050980,1.00148,4480.26,-3.382375,0.457618,0
26,"beta[3,1]",-0.10,1.061980,0.152382,2.315740,1.00069,5354.69,-11.619800,1.350198,0
27,"beta[3,2]",0.20,-0.017256,-0.533289,0.501663,1.00041,11028.60,-1.086282,0.047200,1
28,"beta[4,1]",-0.20,0.170615,-0.084706,0.428168,1.00144,12960.40,-1.853075,0.137355,0
29,"beta[4,2]",0.40,-0.437462,-0.572010,-0.304315,1.00013,10942.40,-2.093655,0.701343,0
30,"beta[5,1]",0.30,-0.298165,-0.693572,0.081711,1.00136,11666.20,-1.993883,0.357801,0
31,"beta[5,2]",-0.30,0.247358,0.060321,0.445525,1.00141,10631.10,-1.824527,0.299601,0
32,"beta[6,1]",-0.10,0.044853,-0.259601,0.347654,1.00051,12490.80,-1.448535,0.020983,1
33,"beta[6,2]",-0.20,0.117881,-0.031347,0.267558,1.00029,12346.80,-1.589405,0.101048,0
34,"beta[7,1]",-0.20,0.151575,-0.057265,0.364234,1.00050,12211.00,-1.757875,0.123605,0
35,"beta[7,2]",-0.10,0.070216,-0.035567,0.180465,1.00043,12029.20,-1.702155,0.028973,0
36,sigma_bk[1],3.70,3.560410,3.004450,4.198390,1.00188,2943.76,-0.037727,0.019485,1
37,sigma_bk[2],3.40,4.479190,1.635330,9.110670,1.02406,422.82,0.317409,1.164651,1
38,sigma_bk[3],4.80,8.206420,5.133520,14.625400,1.00428,1845.21,0.709671,11.603697,0
39,sigma_bk[4],3.10,3.008250,2.646710,3.397010,1.00110,3465.17,-0.029597,0.008418,1
40,sigma_bk[5],6.10,5.925970,5.015490,7.036370,1.00122,2700.77,-0.028530,0.030286,1
41,sigma_bk[6],5.10,5.661620,4.998020,6.391850,1.00113,4129.37,0.110122,0.315417,1
42,sigma_bk[7],1.70,1.607370,1.377130,1.842510,1.00285,2291.56,-0.054488,0.008580,1
43,rho,0.60,-0.053849,-0.138488,0.030578,1.00132,6717.51,-1.089748,0.427518,0
44,"Gamma[1,1]",0.18,0.218999,0.173734,0.268970,1.00968,1499.93,0.216661,0.001521,1
45,"Gamma[1,2]",-0.07,-0.165691,-0.206910,-0.122538,1.00090,6099.69,1.367014,0.009157,0
46,"Gamma[2,1]",0.10,0.125084,0.077570,0.171541,1.00102,4807.90,0.250840,0.000629,1
47,"Gamma[2,2]",0.15,0.160736,0.132081,0.193129,1.00452,1810.21,0.071573,0.000115,1

In [6]:
datasets["s5_shift_global_lap"]

,Parameter,True_Value,Estimate,2.5%,97.5%,R_hat,ESS,Rbias,MSE,Coverage
0,theta1,2.30,-1.893490,-2.483830,-1.374680,1.000620,6645.950,-1.823257,17.585358,0
1,theta2,2.60,-0.377698,-1.115310,0.245286,1.001920,5717.230,-1.145268,8.866685,0
2,theta3,2.90,-0.665130,-1.916400,0.304306,1.000920,4336.720,-1.229355,12.710152,0
3,theta4[1],-4.00,-2.419350,-2.976690,-1.885770,1.001560,3704.710,-0.395162,2.498454,0
4,theta4[2],-1.00,0.276661,-0.243601,0.799449,1.001660,3548.530,-1.276661,1.629863,0
5,theta4[3],2.70,4.164430,3.564620,4.819640,1.002320,3862.760,0.542381,2.144555,0
6,theta5[1],-7.50,-5.811360,-7.329440,-4.564200,1.001200,2826.090,-0.225152,2.851505,0
7,theta5[2],-2.50,-0.606374,-1.610920,0.356392,1.001350,3435.950,-0.757450,3.585819,0
8,theta5[3],2.60,4.555950,3.417940,5.911360,1.002440,3056.030,0.752288,3.825740,0
9,theta6[1],-5.50,-4.498150,-5.338160,-3.721630,1.001000,4288.900,-0.182155,1.003703,0
10,theta6[2],-2.70,-1.690640,-2.404090,-1.002860,1.001270,4135.470,-0.373837,1.018808,0
11,theta6[3],2.50,3.783200,3.027490,4.588880,1.001790,4181.040,0.513280,1.646602,0
12,theta7[1],-4.30,-3.660120,-4.064790,-3.264430,1.000920,4303.490,-0.148809,0.409446,0
13,theta7[2],-1.00,-0.438848,-0.755807,-0.120026,1.001720,3300.130,-0.561152,0.314892,0
14,theta7[3],1.40,1.840690,1.506410,2.181770,1.001930,3547.970,0.314779,0.194208,0
15,lambda[1],1.20,1.759730,1.320520,2.271150,1.003050,4262.340,0.466442,0.313298,0
16,lambda[2],4.00,4.871230,3.445870,7.363950,1.005550,1811.090,0.217807,0.759042,1
17,lambda[3],4.10,7.041820,4.360850,12.964200,1.006610,1249.740,0.717517,8.654305,0
18,lambda[4],3.10,4.864030,4.291190,5.500280,1.002380,3041.730,0.569042,3.111802,0
19,lambda[5],5.20,9.155920,7.498760,11.302100,1.001890,1792.550,0.760754,15.649303,0
20,lambda[6],3.00,5.558630,4.798990,6.421750,1.002660,2254.580,0.852877,6.546587,0
21,lambda[7],1.70,3.062930,2.749550,3.398400,1.001300,3524.430,0.801724,1.857578,0
22,"beta[1,1]",0.30,-0.287030,-0.675117,0.095375,1.000880,13701.400,-1.956767,0.344604,0
23,"beta[1,2]",0.50,-0.520103,-0.729165,-0.319555,1.000590,12209.400,-2.040206,1.040610,0
24,"beta[2,1]",0.10,0.375249,-0.152222,0.974032,1.000950,11746.300,2.752490,0.075762,1
25,"beta[2,2]",0.20,-0.313902,-0.628562,-0.042987,1.000090,8176.500,-2.569510,0.264095,0
26,"beta[3,1]",-0.10,0.611326,-0.108538,1.538120,1.001030,6393.620,-7.113260,0.505985,1
27,"beta[3,2]",0.20,-0.297632,-0.787048,0.081507,1.001230,6055.400,-2.488160,0.247638,0
28,"beta[4,1]",-0.20,0.226663,-0.072657,0.531347,1.000280,15688.600,-2.133315,0.182041,0
29,"beta[4,2]",0.40,-0.441407,-0.597314,-0.288962,0.999657,13560.300,-2.103518,0.707966,0
30,"beta[5,1]",0.30,-0.445996,-0.935614,0.016661,1.000190,13390.500,-2.486653,0.556510,0
31,"beta[5,2]",-0.30,0.277553,0.041966,0.528222,1.000140,12279.600,-1.925177,0.333567,0
32,"beta[6,1]",-0.10,-0.027191,-0.370008,0.315329,1.000360,16110.100,-0.728094,0.005301,1
33,"beta[6,2]",-0.20,0.113226,-0.057707,0.284653,1.000140,15146.200,-1.566130,0.098111,0
34,"beta[7,1]",-0.20,0.128986,-0.104533,0.357583,1.000790,14530.900,-1.644930,0.108232,0
35,"beta[7,2]",-0.10,0.038948,-0.079037,0.159320,1.001360,13283.400,-1.389477,0.019306,0
36,sigma_bk[1],3.70,4.037890,3.378000,4.805260,1.002350,2909.940,0.091322,0.114170,1
37,sigma_bk[2],3.40,3.785600,2.775600,5.360230,1.006370,1739.060,0.113412,0.148687,1
38,sigma_bk[3],4.80,6.342580,4.110800,11.327400,1.005960,1254.770,0.321371,2.379553,1
39,sigma_bk[4],3.10,3.175850,2.756470,3.633750,1.002890,2959.380,0.024468,0.005753,1
40,sigma_bk[5],6.10,6.398090,5.215840,7.889030,1.003670,2031.490,0.048867,0.088858,1
41,sigma_bk[6],5.10,5.519410,4.817200,6.303260,1.004340,2700.810,0.082237,0.175905,1
42,sigma_bk[7],1.70,1.420340,1.150510,1.685410,1.005030,1491.740,-0.164506,0.078210,0
43,rho,0.60,0.036728,-0.061220,0.134683,1.001350,5724.620,-0.938786,0.317275,0
44,"Gamma[1,1]",0.18,0.219877,0.164839,0.289065,1.010700,640.215,0.221539,0.001590,1
45,"Gamma[1,2]",-0.07,-0.034587,-0.089192,0.022173,1.002860,2685.190,-0.505901,0.001254,1
46,"Gamma[2,1]",0.10,0.017630,-0.017775,0.053373,1.002160,2657.780,-0.823697,0.006785,0
47,"Gamma[2,2]",0.15,0.112222,0.092794,0.133027,1.006270,1280.110,-0.251853,0.001427,0
48,c_latent[1],0.50,0.142370,0.111473,0.174391,1.001980,3699.100,-0.715260,0.127899,0
49,c_latent[2],-0.30,-0.040283,-0.060575,-0.020066,1.000850,5707.920,-0.865724,0.067453,0

In [7]:
datasets["s5_shift_global_na"]

,Parameter,True_Value,Estimate,2.5%,97.5%,R_hat,ESS,Rbias,MSE,Coverage
0,theta1,2.30,-1.895080,-2.474430,-1.370450,1.00040,7364.700,-1.823948,17.598696,0
1,theta2,2.60,-0.377781,-1.084920,0.260353,1.00051,6178.080,-1.145300,8.867180,0
2,theta3,2.90,-0.664196,-1.909750,0.257910,1.00177,4131.750,-1.229033,12.703493,0
3,theta4[1],-4.00,-2.423750,-2.975550,-1.875720,1.00061,4458.680,-0.394062,2.484564,0
4,theta4[2],-1.00,0.273580,-0.242567,0.802244,1.00001,4082.880,-1.273580,1.622006,0
5,theta4[3],2.70,4.166430,3.557950,4.838430,1.00044,4314.530,0.543122,2.150417,0
6,theta5[1],-7.50,-5.836350,-7.348870,-4.561820,1.00144,3258.120,-0.221820,2.767731,0
7,theta5[2],-2.50,-0.620254,-1.602370,0.339862,1.00090,3981.580,-0.751898,3.533445,0
8,theta5[3],2.60,4.558660,3.418940,5.920350,1.00122,3417.400,0.753331,3.836349,0
9,theta6[1],-5.50,-4.497370,-5.345290,-3.706290,1.00055,5214.110,-0.182296,1.005267,0
10,theta6[2],-2.70,-1.690530,-2.417940,-0.985839,1.00061,5145.860,-0.373878,1.019030,0
11,theta6[3],2.50,3.779380,3.012380,4.607330,1.00127,4685.590,0.511752,1.636813,0
12,theta7[1],-4.30,-3.663360,-4.076930,-3.265540,0.99990,4761.410,-0.148056,0.405310,0
13,theta7[2],-1.00,-0.441577,-0.762952,-0.118129,1.00062,3944.840,-0.558423,0.311836,0
14,theta7[3],1.40,1.839360,1.511900,2.184370,1.00093,4149.400,0.313829,0.193037,0
15,lambda[1],1.20,1.756940,1.302020,2.286040,1.00054,4576.880,0.464117,0.310182,0
16,lambda[2],4.00,4.850660,3.430590,7.312000,1.00409,1864.530,0.212665,0.723622,1
17,lambda[3],4.10,7.061740,4.262900,13.494700,1.00768,1110.960,0.722376,8.771904,0
18,lambda[4],3.10,4.867080,4.292690,5.503790,1.00321,2992.510,0.570026,3.122572,0
19,lambda[5],5.20,9.184460,7.521890,11.371400,1.00463,1701.540,0.766242,15.875921,0
20,lambda[6],3.00,5.548860,4.783800,6.435830,1.00304,2619.780,0.849620,6.496687,0
21,lambda[7],1.70,3.063390,2.752050,3.397980,1.00256,3691.850,0.801994,1.858832,0
22,"beta[1,1]",0.30,-0.289540,-0.673086,0.091430,1.00052,13617.200,-1.965133,0.347557,0
23,"beta[1,2]",0.50,-0.521633,-0.730113,-0.322156,1.00074,11920.100,-2.043266,1.043734,0
24,"beta[2,1]",0.10,0.371097,-0.153660,0.947234,1.00072,11465.000,2.710970,0.073494,1
25,"beta[2,2]",0.20,-0.314083,-0.621648,-0.041879,1.00014,9404.370,-2.570415,0.264281,0
26,"beta[3,1]",-0.10,0.607598,-0.111207,1.551340,1.00131,5825.430,-7.075980,0.500695,1
27,"beta[3,2]",0.20,-0.293102,-0.787600,0.088475,1.00103,5638.060,-2.465510,0.243150,0
28,"beta[4,1]",-0.20,0.225793,-0.073970,0.519816,1.00055,13852.500,-2.128965,0.181300,0
29,"beta[4,2]",0.40,-0.443087,-0.601997,-0.290738,1.00121,14367.100,-2.107718,0.710796,0
30,"beta[5,1]",0.30,-0.452378,-0.931766,0.008142,1.00009,13580.100,-2.507927,0.566073,0
31,"beta[5,2]",-0.30,0.280087,0.037773,0.530042,1.00017,12653.800,-1.933623,0.336501,0
32,"beta[6,1]",-0.10,-0.031498,-0.368453,0.307296,1.00035,15434.200,-0.685017,0.004692,1
33,"beta[6,2]",-0.20,0.114373,-0.054152,0.285527,1.00075,14464.400,-1.571865,0.098830,0
34,"beta[7,1]",-0.20,0.129823,-0.103061,0.364562,1.00060,13020.500,-1.649115,0.108783,0
35,"beta[7,2]",-0.10,0.039158,-0.080034,0.159804,1.00051,13341.000,-1.391585,0.019365,0
36,sigma_bk[1],3.70,4.039520,3.385920,4.823420,1.00228,3335.410,0.091762,0.115274,1
37,sigma_bk[2],3.40,3.775900,2.729950,5.321100,1.00692,1479.610,0.110559,0.141301,1
38,sigma_bk[3],4.80,6.396550,4.102990,11.629300,1.00983,1229.520,0.332615,2.548972,1
39,sigma_bk[4],3.10,3.175880,2.754320,3.627760,1.00152,3158.110,0.024477,0.005758,1
40,sigma_bk[5],6.10,6.415780,5.223730,7.963560,1.00427,1986.680,0.051767,0.099717,1
41,sigma_bk[6],5.10,5.518410,4.786190,6.348380,1.00208,3413.090,0.082041,0.175067,1
42,sigma_bk[7],1.70,1.423760,1.155370,1.686310,1.00657,1416.240,-0.162494,0.076309,0
43,rho,0.60,0.037947,-0.060021,0.133553,1.00164,5219.930,-0.936754,0.315903,0
44,"Gamma[1,1]",0.18,0.224046,0.163761,0.294141,1.00982,615.148,0.244700,0.001940,1
45,"Gamma[1,2]",-0.07,-0.034874,-0.089459,0.022154,1.00140,3084.470,-0.501796,0.001234,1
46,"Gamma[2,1]",0.10,0.018103,-0.017389,0.054836,1.00218,3213.420,-0.818970,0.006707,0
47,"Gamma[2,2]",0.15,0.112281,0.092419,0.133241,1.00920,1322.210,-0.251460,0.001423,0
48,c_latent[1],0.50,0.142598,0.110823,0.174882,1.00111,3792.400,-0.714804,0.127736,0
49,c_latent[2],-0.30,-0.040452,-0.060588,-0.020148,1.00059,5648.980,-0.865161,0.067365,0

In [8]:
# ---------------------------------------------------------
# 2. MERGE DATASETS BY SCENARIO
# ---------------------------------------------------------

def merge_by_scenario(datasets):
    scenario_groups = {}

    # Step 1: group datasets by scenario
    for name, df in datasets.items():
        if df is None:
            continue
        
        scenario = name.split('_')[0]   # s2, s3, s5
        
        if scenario not in scenario_groups:
            scenario_groups[scenario] = []
        
        # rename columns except Parameter
        df = df.copy()
        rename_dict = {
            col: f"{col}_{name}" for col in df.columns if col != "Parameter"
        }
        df = df.rename(columns=rename_dict)
        
        scenario_groups[scenario].append(df)

    # Step 2: merge within each scenario
    merged_results = {}
    
    for scenario, dfs in scenario_groups.items():
        merged_df = dfs[0]
        
        for df in dfs[1:]:
            merged_df = merged_df.merge(df, on="Parameter", how="outer")
        
        merged_results[scenario] = merged_df

    return merged_results


merged_scenarios = merge_by_scenario(datasets)

print("\n=== MERGED DATASETS ===")
for k, v in merged_scenarios.items():
    print(f"{k}: {v.shape}")

=== MERGED DATASETS ===
s2: (48, 10)
s3: (48, 19)
s5: (50, 19)

In [10]:
merged_scenarios["s3"]

,Parameter,True_Value_s3_fix_na_lap,Estimate_s3_fix_na_lap,2.5%_s3_fix_na_lap,97.5%_s3_fix_na_lap,R_hat_s3_fix_na_lap,ESS_s3_fix_na_lap,Rbias_s3_fix_na_lap,MSE_s3_fix_na_lap,Coverage_s3_fix_na_lap,True_Value_s3_fix_na_na,Estimate_s3_fix_na_na,2.5%_s3_fix_na_na,97.5%_s3_fix_na_na,R_hat_s3_fix_na_na,ESS_s3_fix_na_na,Rbias_s3_fix_na_na,MSE_s3_fix_na_na,Coverage_s3_fix_na_na
0,"Gamma[1,1]",0.18,0.216356,0.170942,0.267716,1.006500,1393.350,0.201978,0.001322,1,0.18,0.218999,0.173734,0.268970,1.00968,1499.93,0.216661,0.001521,1
1,"Gamma[1,2]",-0.07,-0.166734,-0.208660,-0.124016,1.000840,5583.640,1.381914,0.009357,0,-0.07,-0.165691,-0.206910,-0.122538,1.00090,6099.69,1.367014,0.009157,0
2,"Gamma[2,1]",0.10,0.126202,0.077348,0.174865,1.002790,4383.250,0.262020,0.000687,1,0.10,0.125084,0.077570,0.171541,1.00102,4807.90,0.250840,0.000629,1
3,"Gamma[2,2]",0.15,0.160972,0.131943,0.193084,1.005800,1750.630,0.073147,0.000120,1,0.15,0.160736,0.132081,0.193129,1.00452,1810.21,0.071573,0.000115,1
4,"beta[1,1]",0.30,-0.237668,-0.583645,0.103592,0.999984,11115.700,-1.792227,0.289087,0,0.30,-0.233798,-0.576062,0.101031,1.00170,13106.50,-1.779327,0.284940,0
5,"beta[1,2]",0.50,-0.436249,-0.623745,-0.253361,1.000480,10925.500,-1.872498,0.876562,0,0.50,-0.435258,-0.626159,-0.246709,1.00041,11032.90,-1.870516,0.874708,0
6,"beta[2,1]",0.10,-0.870916,-2.282920,0.118976,1.001920,5624.070,-9.709160,0.942678,1,0.10,-0.868158,-2.248410,0.124330,1.00149,4556.57,-9.681580,0.937330,1
7,"beta[2,2]",0.20,-0.473216,-1.238430,0.059103,1.000980,5207.020,-3.366080,0.453220,0,0.20,-0.476475,-1.300630,0.050980,1.00148,4480.26,-3.382375,0.457618,0
8,"beta[3,1]",-0.10,1.071090,0.157343,2.387070,1.001980,5282.410,-11.710900,1.371452,0,-0.10,1.061980,0.152382,2.315740,1.00069,5354.69,-11.619800,1.350198,0
9,"beta[3,2]",0.20,-0.015210,-0.532983,0.496828,1.000400,10716.900,-1.076052,0.046316,1,0.20,-0.017256,-0.533289,0.501663,1.00041,11028.60,-1.086282,0.047200,1
10,"beta[4,1]",-0.20,0.170269,-0.093905,0.433440,1.000070,12500.400,-1.851345,0.137099,0,-0.20,0.170615,-0.084706,0.428168,1.00144,12960.40,-1.853075,0.137355,0
11,"beta[4,2]",0.40,-0.436169,-0.570320,-0.304155,1.000900,12593.700,-2.090422,0.699179,0,0.40,-0.437462,-0.572010,-0.304315,1.00013,10942.40,-2.093655,0.701343,0
12,"beta[5,1]",0.30,-0.297531,-0.682285,0.079041,1.000240,12397.300,-1.991770,0.357043,0,0.30,-0.298165,-0.693572,0.081711,1.00136,11666.20,-1.993883,0.357801,0
13,"beta[5,2]",-0.30,0.247275,0.056888,0.446500,1.000600,9612.300,-1.824250,0.299510,0,-0.30,0.247358,0.060321,0.445525,1.00141,10631.10,-1.824527,0.299601,0
14,"beta[6,1]",-0.10,0.041460,-0.266545,0.340730,1.000980,12642.500,-1.414605,0.020011,1,-0.10,0.044853,-0.259601,0.347654,1.00051,12490.80,-1.448535,0.020983,1
15,"beta[6,2]",-0.20,0.117026,-0.034628,0.267798,1.000250,11818.500,-1.585130,0.100505,0,-0.20,0.117881,-0.031347,0.267558,1.00029,12346.80,-1.589405,0.101048,0
16,"beta[7,1]",-0.20,0.152159,-0.059361,0.365557,1.001110,12831.600,-1.760795,0.124016,0,-0.20,0.151575,-0.057265,0.364234,1.00050,12211.00,-1.757875,0.123605,0
17,"beta[7,2]",-0.10,0.070143,-0.038988,0.179013,1.000220,11518.200,-1.701434,0.028949,0,-0.10,0.070216,-0.035567,0.180465,1.00043,12029.20,-1.702155,0.028973,0
18,lambda[1],1.20,1.584050,1.236830,1.980310,1.000810,5964.500,0.320042,0.147494,0,1.20,1.575740,1.225960,1.974810,1.00117,5583.38,0.313117,0.141181,0
19,lambda[2],4.00,11.740300,6.535560,23.166100,1.009230,1288.950,1.935075,59.912244,0,4.00,11.771300,6.549860,23.620900,1.00593,1205.32,1.942825,60.393104,0
20,lambda[3],4.10,9.460880,5.782800,17.265400,1.006920,1555.680,1.307532,28.739034,0,4.10,9.423810,5.742460,17.073700,1.00430,1670.68,1.298490,28.342953,0
21,lambda[4],3.10,3.464980,3.070660,3.903050,1.001370,4376.730,0.117735,0.133210,1,3.10,3.473510,3.072230,3.919770,1.00174,3543.29,0.120487,0.139510,1
22,lambda[5],5.20,6.163490,5.158950,7.422410,1.005730,1887.210,0.185287,0.928313,1,5.20,6.196150,5.177580,7.428670,1.00171,2310.71,0.191567,0.992315,1
23,lambda[6],3.00,4.055460,3.520690,4.662520,1.002090,3655.700,0.351820,1.113996,0,3.00,4.059840,3.527690,4.663760,1.00283,2970.34,0.353280,1.123261,0
24,lambda[7],1.70,2.301800,2.057450,2.559560,1.001130,4612.800,0.354000,0.362163,0,1.70,2.303510,2.055330,2.572470,1.00164,4359.85,0.355006,0.364224,0
25,rho,0.60,-0.053513,-0.137899,0.029175,1.000880,6647.530,-1.089188,0.427079,0,0.60,-0.053849,-0.138488,0.030578,1.00132,6717.51,-1.089748,0.427518,0
26,sigma_bk[1],3.70,3.565410,3.025330,4.197000,1.001440,3558.670,-0.036376,0.018114,1,3.70,3.560410,3.004450,4.198390,1.00188,2943.76,-0.037727,0.019485,1
27,sigma_bk[2],3.40,4.442170,1.626710,8.932600,1.015560,614.439,0.306521,1.086118,1,3.40,4.479190,1.635330,9.110670,1.02406,422.82,0.317409,1.164651,1
28,sigma_bk[3],4.80,8.230160,5.113270,14.767200,1.005970,1755.120,0.714617,11.765998,0,4.80,8.206420,5.133520,14.625400,1.00428,1845.21,0.709671,11.603697,0
29,sigma_bk[4],3.10,3.002040,2.641520,3.389480,1.000880,3891.650,-0.031600,0.009596,1,3.10,3.008250,2.646710,3.397010,1.00110,3465.17,-0.029597,0.008418,1
30,sigma_bk[5],6.10,5.908900,5.005870,7.035490,1.004080,2264.280,-0.031328,0.036519,1,6.10,5.925970,5.015490,7.036370,1.00122,2700.77,-0.028530,0.030286,1
31,sigma_bk[6],5.10,5.658090,4.985760,6.398610,1.000900,4938.460,0.109429,0.311464,1,5.10,5.661620,4.998020,6.391850,1.00113,4129.37,0.110122,0.315417,1
32,sigma_bk[7],1.70,1.611860,1.381590,1.853890,1.002040,2437.170,-0.051847,0.007769,1,1.70,1.607370,1.377130,1.842510,1.00285,2291.56,-0.054488,0.008580,1
33,theta1,2.30,-1.478710,-1.952960,-1.040520,1.000280,7398.710,-1.642917,14.278649,0,2.30,-1.475760,-1.958370,-1.037660,1.00010,7890.26,-1.641635,14.256364,0
34,theta2,2.60,0.296946,-0.853474,1.662470,1.001630,6042.630,-0.885790,5.304058,0,2.60,0.312047,-0.885626,1.639270,1.00140,5403.47,-0.879982,5.234729,0
35,theta3,2.90,-0.628147,-2.003370,0.511789,1.002570,5462.660,-1.216602,12.447821,0,2.90,-0.606928,-1.936180,0.527265,1.00111,5437.87,-1.209286,12.298544,0
36,theta4[1],-4.00,-1.294870,-1.734900,-0.860695,1.000960,5635.010,-0.676283,7.317728,0,-4.00,-1.301050,-1.749710,-0.853032,1.00014,5653.15,-0.674737,7.284331,0
37,theta4[2],-1.00,1.418610,0.972412,1.875210,1.001210,5844.980,-2.418610,5.849674,0,-1.00,1.413880,0.962190,1.877330,1.00029,5387.58,-2.413880,5.826817,0
38,theta4[3],2.70,4.835970,4.287830,5.420080,1.000790,6381.600,0.791100,4.562368,0,2.70,4.834740,4.287610,5.421720,1.00059,5413.69,0.790644,4.557115,0
39,theta5[1],-7.50,-3.678050,-4.642820,-2.805690,1.000700,5238.560,-0.509593,14.607302,0,-7.50,-3.698330,-4.653580,-2.837640,1.00206,5095.08,-0.506889,14.452695,0
40,theta5[2],-2.50,1.241530,0.470458,2.070370,1.001770,5016.180,-1.496612,13.999047,0,-2.50,1.234870,0.456002,2.079230,1.00184,4359.70,-1.493948,13.949254,0
41,theta5[3],2.60,6.083560,5.026600,7.340850,1.003420,3463.930,1.339831,12.135190,0,2.60,6.092590,5.021690,7.376750,1.00088,3648.22,1.343304,12.198185,0
42,theta6[1],-5.50,-3.470090,-4.190420,-2.802470,1.000270,7201.490,-0.369075,4.120535,0,-5.50,-3.474080,-4.182220,-2.789790,1.00090,7033.43,-0.368349,4.104352,0
43,theta6[2],-2.70,-0.298816,-0.942555,0.331927,1.000550,6641.080,-0.889327,5.765685,0,-2.70,-0.301852,-0.940903,0.316937,1.00053,7118.85,-0.888203,5.751114,0
44,theta6[3],2.50,5.026310,4.271270,5.828950,1.000600,5979.070,1.010524,6.382242,0,2.50,5.023300,4.278750,5.832140,1.00117,6580.35,1.009320,6.367043,0
45,theta7[1],-4.30,-3.012310,-3.351320,-2.682300,1.000520,6211.000,-0.299463,1.658146,0,-4.30,-3.016760,-3.353400,-2.692070,1.00105,6284.87,-0.298428,1.646705,0
46,theta7[2],-1.00,0.321693,0.035220,0.608484,1.000750,5609.410,-1.321693,1.746872,0,-1.00,0.317442,0.032746,0.606356,1.00151,5222.22,-1.317442,1.735653,0
47,theta7[3],1.40,2.671330,2.349280,3.001410,1.000920,5667.330,0.908093,1.616280,0,1.40,2.665770,2.346680,2.991070,1.00117,5722.31,0.904121,1.602174,0

In [11]:
from collections import defaultdict

scenario_groups = defaultdict(dict)

for name, df in datasets.items():
    if df is None:
        continue
    
    scenario = name.split('_')[0]   # S2, S3, S5
    model = "_".join(name.split('_')[1:])  # model type
    
    scenario_groups[scenario][model] = df

In [12]:
merged_results = {}

for scenario, models in scenario_groups.items():
    
    merged_df = None
    
    for model_name, df in models.items():
        
        df_model = df.copy()
        
        # Rename columns except Parameter
        rename_cols = {
            c: f"{model_name}_{c}" 
            for c in df_model.columns if c != "Parameter"
        }
        
        df_model = df_model.rename(columns=rename_cols)
        
        if merged_df is None:
            merged_df = df_model
        else:
            merged_df = pd.merge(
                merged_df,
                df_model,
                on="Parameter",
                how="outer"
            )
    
    merged_results[scenario] = merged_df

In [13]:
def reorder_columns(df):
    
    param_col = ['Parameter']
    other_cols = [c for c in df.columns if c != 'Parameter']
    
    metrics = sorted(set(c.split('_')[-1] for c in other_cols))
    
    ordered = []
    
    for metric in metrics:
        metric_cols = [c for c in other_cols if c.endswith(metric)]
        ordered.extend(sorted(metric_cols))
    
    return df[param_col + ordered]

for scenario in merged_results:
    merged_results[scenario] = reorder_columns(merged_results[scenario])

In [14]:
merged_results["s3"]

,Parameter,fix_na_lap_2.5%,fix_na_na_2.5%,fix_na_lap_97.5%,fix_na_na_97.5%,fix_na_lap_Coverage,fix_na_na_Coverage,fix_na_lap_ESS,fix_na_na_ESS,fix_na_lap_Estimate,fix_na_na_Estimate,fix_na_lap_MSE,fix_na_na_MSE,fix_na_lap_Rbias,fix_na_na_Rbias,fix_na_lap_True_Value,fix_na_na_True_Value,fix_na_lap_R_hat,fix_na_na_R_hat
0,"Gamma[1,1]",0.170942,0.173734,0.267716,0.268970,1,1,1393.350,1499.93,0.216356,0.218999,0.001322,0.001521,0.201978,0.216661,0.18,0.18,1.006500,1.00968
1,"Gamma[1,2]",-0.208660,-0.206910,-0.124016,-0.122538,0,0,5583.640,6099.69,-0.166734,-0.165691,0.009357,0.009157,1.381914,1.367014,-0.07,-0.07,1.000840,1.00090
2,"Gamma[2,1]",0.077348,0.077570,0.174865,0.171541,1,1,4383.250,4807.90,0.126202,0.125084,0.000687,0.000629,0.262020,0.250840,0.10,0.10,1.002790,1.00102
3,"Gamma[2,2]",0.131943,0.132081,0.193084,0.193129,1,1,1750.630,1810.21,0.160972,0.160736,0.000120,0.000115,0.073147,0.071573,0.15,0.15,1.005800,1.00452
4,"beta[1,1]",-0.583645,-0.576062,0.103592,0.101031,0,0,11115.700,13106.50,-0.237668,-0.233798,0.289087,0.284940,-1.792227,-1.779327,0.30,0.30,0.999984,1.00170
5,"beta[1,2]",-0.623745,-0.626159,-0.253361,-0.246709,0,0,10925.500,11032.90,-0.436249,-0.435258,0.876562,0.874708,-1.872498,-1.870516,0.50,0.50,1.000480,1.00041
6,"beta[2,1]",-2.282920,-2.248410,0.118976,0.124330,1,1,5624.070,4556.57,-0.870916,-0.868158,0.942678,0.937330,-9.709160,-9.681580,0.10,0.10,1.001920,1.00149
7,"beta[2,2]",-1.238430,-1.300630,0.059103,0.050980,0,0,5207.020,4480.26,-0.473216,-0.476475,0.453220,0.457618,-3.366080,-3.382375,0.20,0.20,1.000980,1.00148
8,"beta[3,1]",0.157343,0.152382,2.387070,2.315740,0,0,5282.410,5354.69,1.071090,1.061980,1.371452,1.350198,-11.710900,-11.619800,-0.10,-0.10,1.001980,1.00069
9,"beta[3,2]",-0.532983,-0.533289,0.496828,0.501663,1,1,10716.900,11028.60,-0.015210,-0.017256,0.046316,0.047200,-1.076052,-1.086282,0.20,0.20,1.000400,1.00041
10,"beta[4,1]",-0.093905,-0.084706,0.433440,0.428168,0,0,12500.400,12960.40,0.170269,0.170615,0.137099,0.137355,-1.851345,-1.853075,-0.20,-0.20,1.000070,1.00144
11,"beta[4,2]",-0.570320,-0.572010,-0.304155,-0.304315,0,0,12593.700,10942.40,-0.436169,-0.437462,0.699179,0.701343,-2.090422,-2.093655,0.40,0.40,1.000900,1.00013
12,"beta[5,1]",-0.682285,-0.693572,0.079041,0.081711,0,0,12397.300,11666.20,-0.297531,-0.298165,0.357043,0.357801,-1.991770,-1.993883,0.30,0.30,1.000240,1.00136
13,"beta[5,2]",0.056888,0.060321,0.446500,0.445525,0,0,9612.300,10631.10,0.247275,0.247358,0.299510,0.299601,-1.824250,-1.824527,-0.30,-0.30,1.000600,1.00141
14,"beta[6,1]",-0.266545,-0.259601,0.340730,0.347654,1,1,12642.500,12490.80,0.041460,0.044853,0.020011,0.020983,-1.414605,-1.448535,-0.10,-0.10,1.000980,1.00051
15,"beta[6,2]",-0.034628,-0.031347,0.267798,0.267558,0,0,11818.500,12346.80,0.117026,0.117881,0.100505,0.101048,-1.585130,-1.589405,-0.20,-0.20,1.000250,1.00029
16,"beta[7,1]",-0.059361,-0.057265,0.365557,0.364234,0,0,12831.600,12211.00,0.152159,0.151575,0.124016,0.123605,-1.760795,-1.757875,-0.20,-0.20,1.001110,1.00050
17,"beta[7,2]",-0.038988,-0.035567,0.179013,0.180465,0,0,11518.200,12029.20,0.070143,0.070216,0.028949,0.028973,-1.701434,-1.702155,-0.10,-0.10,1.000220,1.00043
18,lambda[1],1.236830,1.225960,1.980310,1.974810,0,0,5964.500,5583.38,1.584050,1.575740,0.147494,0.141181,0.320042,0.313117,1.20,1.20,1.000810,1.00117
19,lambda[2],6.535560,6.549860,23.166100,23.620900,0,0,1288.950,1205.32,11.740300,11.771300,59.912244,60.393104,1.935075,1.942825,4.00,4.00,1.009230,1.00593
20,lambda[3],5.782800,5.742460,17.265400,17.073700,0,0,1555.680,1670.68,9.460880,9.423810,28.739034,28.342953,1.307532,1.298490,4.10,4.10,1.006920,1.00430
21,lambda[4],3.070660,3.072230,3.903050,3.919770,1,1,4376.730,3543.29,3.464980,3.473510,0.133210,0.139510,0.117735,0.120487,3.10,3.10,1.001370,1.00174
22,lambda[5],5.158950,5.177580,7.422410,7.428670,1,1,1887.210,2310.71,6.163490,6.196150,0.928313,0.992315,0.185287,0.191567,5.20,5.20,1.005730,1.00171
23,lambda[6],3.520690,3.527690,4.662520,4.663760,0,0,3655.700,2970.34,4.055460,4.059840,1.113996,1.123261,0.351820,0.353280,3.00,3.00,1.002090,1.00283
24,lambda[7],2.057450,2.055330,2.559560,2.572470,0,0,4612.800,4359.85,2.301800,2.303510,0.362163,0.364224,0.354000,0.355006,1.70,1.70,1.001130,1.00164
25,rho,-0.137899,-0.138488,0.029175,0.030578,0,0,6647.530,6717.51,-0.053513,-0.053849,0.427079,0.427518,-1.089188,-1.089748,0.60,0.60,1.000880,1.00132
26,sigma_bk[1],3.025330,3.004450,4.197000,4.198390,1,1,3558.670,2943.76,3.565410,3.560410,0.018114,0.019485,-0.036376,-0.037727,3.70,3.70,1.001440,1.00188
27,sigma_bk[2],1.626710,1.635330,8.932600,9.110670,1,1,614.439,422.82,4.442170,4.479190,1.086118,1.164651,0.306521,0.317409,3.40,3.40,1.015560,1.02406
28,sigma_bk[3],5.113270,5.133520,14.767200,14.625400,0,0,1755.120,1845.21,8.230160,8.206420,11.765998,11.603697,0.714617,0.709671,4.80,4.80,1.005970,1.00428
29,sigma_bk[4],2.641520,2.646710,3.389480,3.397010,1,1,3891.650,3465.17,3.002040,3.008250,0.009596,0.008418,-0.031600,-0.029597,3.10,3.10,1.000880,1.00110
30,sigma_bk[5],5.005870,5.015490,7.035490,7.036370,1,1,2264.280,2700.77,5.908900,5.925970,0.036519,0.030286,-0.031328,-0.028530,6.10,6.10,1.004080,1.00122
31,sigma_bk[6],4.985760,4.998020,6.398610,6.391850,1,1,4938.460,4129.37,5.658090,5.661620,0.311464,0.315417,0.109429,0.110122,5.10,5.10,1.000900,1.00113
32,sigma_bk[7],1.381590,1.377130,1.853890,1.842510,1,1,2437.170,2291.56,1.611860,1.607370,0.007769,0.008580,-0.051847,-0.054488,1.70,1.70,1.002040,1.00285
33,theta1,-1.952960,-1.958370,-1.040520,-1.037660,0,0,7398.710,7890.26,-1.478710,-1.475760,14.278649,14.256364,-1.642917,-1.641635,2.30,2.30,1.000280,1.00010
34,theta2,-0.853474,-0.885626,1.662470,1.639270,0,0,6042.630,5403.47,0.296946,0.312047,5.304058,5.234729,-0.885790,-0.879982,2.60,2.60,1.001630,1.00140
35,theta3,-2.003370,-1.936180,0.511789,0.527265,0,0,5462.660,5437.87,-0.628147,-0.606928,12.447821,12.298544,-1.216602,-1.209286,2.90,2.90,1.002570,1.00111
36,theta4[1],-1.734900,-1.749710,-0.860695,-0.853032,0,0,5635.010,5653.15,-1.294870,-1.301050,7.317728,7.284331,-0.676283,-0.674737,-4.00,-4.00,1.000960,1.00014
37,theta4[2],0.972412,0.962190,1.875210,1.877330,0,0,5844.980,5387.58,1.418610,1.413880,5.849674,5.826817,-2.418610,-2.413880,-1.00,-1.00,1.001210,1.00029
38,theta4[3],4.287830,4.287610,5.420080,5.421720,0,0,6381.600,5413.69,4.835970,4.834740,4.562368,4.557115,0.791100,0.790644,2.70,2.70,1.000790,1.00059
39,theta5[1],-4.642820,-4.653580,-2.805690,-2.837640,0,0,5238.560,5095.08,-3.678050,-3.698330,14.607302,14.452695,-0.509593,-0.506889,-7.50,-7.50,1.000700,1.00206
40,theta5[2],0.470458,0.456002,2.070370,2.079230,0,0,5016.180,4359.70,1.241530,1.234870,13.999047,13.949254,-1.496612,-1.493948,-2.50,-2.50,1.001770,1.00184
41,theta5[3],5.026600,5.021690,7.340850,7.376750,0,0,3463.930,3648.22,6.083560,6.092590,12.135190,12.198185,1.339831,1.343304,2.60,2.60,1.003420,1.00088
42,theta6[1],-4.190420,-4.182220,-2.802470,-2.789790,0,0,7201.490,7033.43,-3.470090,-3.474080,4.120535,4.104352,-0.369075,-0.368349,-5.50,-5.50,1.000270,1.00090
43,theta6[2],-0.942555,-0.940903,0.331927,0.316937,0,0,6641.080,7118.85,-0.298816,-0.301852,5.765685,5.751114,-0.889327,-0.888203,-2.70,-2.70,1.000550,1.00053
44,theta6[3],4.271270,4.278750,5.828950,5.832140,0,0,5979.070,6580.35,5.026310,5.023300,6.382242,6.367043,1.010524,1.009320,2.50,2.50,1.000600,1.00117
45,theta7[1],-3.351320,-3.353400,-2.682300,-2.692070,0,0,6211.000,6284.87,-3.012310,-3.016760,1.658146,1.646705,-0.299463,-0.298428,-4.30,-4.30,1.000520,1.00105
46,theta7[2],0.035220,0.032746,0.608484,0.606356,0,0,5609.410,5222.22,0.321693,0.317442,1.746872,1.735653,-1.321693,-1.317442,-1.00,-1.00,1.000750,1.00151
47,theta7[3],2.349280,2.346680,3.001410,2.991070,0,0,5667.330,5722.31,2.671330,2.665770,1.616280,1.602174,0.908093,0.904121,1.40,1.40,1.000920,1.00117

In [15]:
merged_results["s5"]

,Parameter,shift_global_lap_2.5%,shift_global_na_2.5%,shift_global_lap_97.5%,shift_global_na_97.5%,shift_global_lap_Coverage,shift_global_na_Coverage,shift_global_lap_ESS,shift_global_na_ESS,shift_global_lap_Estimate,shift_global_na_Estimate,shift_global_lap_MSE,shift_global_na_MSE,shift_global_lap_Rbias,shift_global_na_Rbias,shift_global_lap_True_Value,shift_global_na_True_Value,shift_global_lap_R_hat,shift_global_na_R_hat
0,"Gamma[1,1]",0.164839,0.163761,0.289065,0.294141,1,1,640.215,615.148,0.219877,0.224046,0.001590,0.001940,0.221539,0.244700,0.18,0.18,1.010700,1.00982
1,"Gamma[1,2]",-0.089192,-0.089459,0.022173,0.022154,1,1,2685.190,3084.470,-0.034587,-0.034874,0.001254,0.001234,-0.505901,-0.501796,-0.07,-0.07,1.002860,1.00140
2,"Gamma[2,1]",-0.017775,-0.017389,0.053373,0.054836,0,0,2657.780,3213.420,0.017630,0.018103,0.006785,0.006707,-0.823697,-0.818970,0.10,0.10,1.002160,1.00218
3,"Gamma[2,2]",0.092794,0.092419,0.133027,0.133241,0,0,1280.110,1322.210,0.112222,0.112281,0.001427,0.001423,-0.251853,-0.251460,0.15,0.15,1.006270,1.00920
4,"beta[1,1]",-0.675117,-0.673086,0.095375,0.091430,0,0,13701.400,13617.200,-0.287030,-0.289540,0.344604,0.347557,-1.956767,-1.965133,0.30,0.30,1.000880,1.00052
5,"beta[1,2]",-0.729165,-0.730113,-0.319555,-0.322156,0,0,12209.400,11920.100,-0.520103,-0.521633,1.040610,1.043734,-2.040206,-2.043266,0.50,0.50,1.000590,1.00074
6,"beta[2,1]",-0.152222,-0.153660,0.974032,0.947234,1,1,11746.300,11465.000,0.375249,0.371097,0.075762,0.073494,2.752490,2.710970,0.10,0.10,1.000950,1.00072
7,"beta[2,2]",-0.628562,-0.621648,-0.042987,-0.041879,0,0,8176.500,9404.370,-0.313902,-0.314083,0.264095,0.264281,-2.569510,-2.570415,0.20,0.20,1.000090,1.00014
8,"beta[3,1]",-0.108538,-0.111207,1.538120,1.551340,1,1,6393.620,5825.430,0.611326,0.607598,0.505985,0.500695,-7.113260,-7.075980,-0.10,-0.10,1.001030,1.00131
9,"beta[3,2]",-0.787048,-0.787600,0.081507,0.088475,0,0,6055.400,5638.060,-0.297632,-0.293102,0.247638,0.243150,-2.488160,-2.465510,0.20,0.20,1.001230,1.00103
10,"beta[4,1]",-0.072657,-0.073970,0.531347,0.519816,0,0,15688.600,13852.500,0.226663,0.225793,0.182041,0.181300,-2.133315,-2.128965,-0.20,-0.20,1.000280,1.00055
11,"beta[4,2]",-0.597314,-0.601997,-0.288962,-0.290738,0,0,13560.300,14367.100,-0.441407,-0.443087,0.707966,0.710796,-2.103518,-2.107718,0.40,0.40,0.999657,1.00121
12,"beta[5,1]",-0.935614,-0.931766,0.016661,0.008142,0,0,13390.500,13580.100,-0.445996,-0.452378,0.556510,0.566073,-2.486653,-2.507927,0.30,0.30,1.000190,1.00009
13,"beta[5,2]",0.041966,0.037773,0.528222,0.530042,0,0,12279.600,12653.800,0.277553,0.280087,0.333567,0.336501,-1.925177,-1.933623,-0.30,-0.30,1.000140,1.00017
14,"beta[6,1]",-0.370008,-0.368453,0.315329,0.307296,1,1,16110.100,15434.200,-0.027191,-0.031498,0.005301,0.004692,-0.728094,-0.685017,-0.10,-0.10,1.000360,1.00035
15,"beta[6,2]",-0.057707,-0.054152,0.284653,0.285527,0,0,15146.200,14464.400,0.113226,0.114373,0.098111,0.098830,-1.566130,-1.571865,-0.20,-0.20,1.000140,1.00075
16,"beta[7,1]",-0.104533,-0.103061,0.357583,0.364562,0,0,14530.900,13020.500,0.128986,0.129823,0.108232,0.108783,-1.644930,-1.649115,-0.20,-0.20,1.000790,1.00060
17,"beta[7,2]",-0.079037,-0.080034,0.159320,0.159804,0,0,13283.400,13341.000,0.038948,0.039158,0.019306,0.019365,-1.389477,-1.391585,-0.10,-0.10,1.001360,1.00051
18,c_latent[1],0.111473,0.110823,0.174391,0.174882,0,0,3699.100,3792.400,0.142370,0.142598,0.127899,0.127736,-0.715260,-0.714804,0.50,0.50,1.001980,1.00111
19,c_latent[2],-0.060575,-0.060588,-0.020066,-0.020148,0,0,5707.920,5648.980,-0.040283,-0.040452,0.067453,0.067365,-0.865724,-0.865161,-0.30,-0.30,1.000850,1.00059
20,lambda[1],1.320520,1.302020,2.271150,2.286040,0,0,4262.340,4576.880,1.759730,1.756940,0.313298,0.310182,0.466442,0.464117,1.20,1.20,1.003050,1.00054
21,lambda[2],3.445870,3.430590,7.363950,7.312000,1,1,1811.090,1864.530,4.871230,4.850660,0.759042,0.723622,0.217807,0.212665,4.00,4.00,1.005550,1.00409
22,lambda[3],4.360850,4.262900,12.964200,13.494700,0,0,1249.740,1110.960,7.041820,7.061740,8.654305,8.771904,0.717517,0.722376,4.10,4.10,1.006610,1.00768
23,lambda[4],4.291190,4.292690,5.500280,5.503790,0,0,3041.730,2992.510,4.864030,4.867080,3.111802,3.122572,0.569042,0.570026,3.10,3.10,1.002380,1.00321
24,lambda[5],7.498760,7.521890,11.302100,11.371400,0,0,1792.550,1701.540,9.155920,9.184460,15.649303,15.875921,0.760754,0.766242,5.20,5.20,1.001890,1.00463
25,lambda[6],4.798990,4.783800,6.421750,6.435830,0,0,2254.580,2619.780,5.558630,5.548860,6.546587,6.496687,0.852877,0.849620,3.00,3.00,1.002660,1.00304
26,lambda[7],2.749550,2.752050,3.398400,3.397980,0,0,3524.430,3691.850,3.062930,3.063390,1.857578,1.858832,0.801724,0.801994,1.70,1.70,1.001300,1.00256
27,rho,-0.061220,-0.060021,0.134683,0.133553,0,0,5724.620,5219.930,0.036728,0.037947,0.317275,0.315903,-0.938786,-0.936754,0.60,0.60,1.001350,1.00164
28,sigma_bk[1],3.378000,3.385920,4.805260,4.823420,1,1,2909.940,3335.410,4.037890,4.039520,0.114170,0.115274,0.091322,0.091762,3.70,3.70,1.002350,1.00228
29,sigma_bk[2],2.775600,2.729950,5.360230,5.321100,1,1,1739.060,1479.610,3.785600,3.775900,0.148687,0.141301,0.113412,0.110559,3.40,3.40,1.006370,1.00692
30,sigma_bk[3],4.110800,4.102990,11.327400,11.629300,1,1,1254.770,1229.520,6.342580,6.396550,2.379553,2.548972,0.321371,0.332615,4.80,4.80,1.005960,1.00983
31,sigma_bk[4],2.756470,2.754320,3.633750,3.627760,1,1,2959.380,3158.110,3.175850,3.175880,0.005753,0.005758,0.024468,0.024477,3.10,3.10,1.002890,1.00152
32,sigma_bk[5],5.215840,5.223730,7.889030,7.963560,1,1,2031.490,1986.680,6.398090,6.415780,0.088858,0.099717,0.048867,0.051767,6.10,6.10,1.003670,1.00427
33,sigma_bk[6],4.817200,4.786190,6.303260,6.348380,1,1,2700.810,3413.090,5.519410,5.518410,0.175905,0.175067,0.082237,0.082041,5.10,5.10,1.004340,1.00208
34,sigma_bk[7],1.150510,1.155370,1.685410,1.686310,0,0,1491.740,1416.240,1.420340,1.423760,0.078210,0.076309,-0.164506,-0.162494,1.70,1.70,1.005030,1.00657
35,theta1,-2.483830,-2.474430,-1.374680,-1.370450,0,0,6645.950,7364.700,-1.893490,-1.895080,17.585358,17.598696,-1.823257,-1.823948,2.30,2.30,1.000620,1.00040
36,theta2,-1.115310,-1.084920,0.245286,0.260353,0,0,5717.230,6178.080,-0.377698,-0.377781,8.866685,8.867180,-1.145268,-1.145300,2.60,2.60,1.001920,1.00051
37,theta3,-1.916400,-1.909750,0.304306,0.257910,0,0,4336.720,4131.750,-0.665130,-0.664196,12.710152,12.703493,-1.229355,-1.229033,2.90,2.90,1.000920,1.00177
38,theta4[1],-2.976690,-2.975550,-1.885770,-1.875720,0,0,3704.710,4458.680,-2.419350,-2.423750,2.498454,2.484564,-0.395162,-0.394062,-4.00,-4.00,1.001560,1.00061
39,theta4[2],-0.243601,-0.242567,0.799449,0.802244,0,0,3548.530,4082.880,0.276661,0.273580,1.629863,1.622006,-1.276661,-1.273580,-1.00,-1.00,1.001660,1.00001
40,theta4[3],3.564620,3.557950,4.819640,4.838430,0,0,3862.760,4314.530,4.164430,4.166430,2.144555,2.150417,0.542381,0.543122,2.70,2.70,1.002320,1.00044
41,theta5[1],-7.329440,-7.348870,-4.564200,-4.561820,0,0,2826.090,3258.120,-5.811360,-5.836350,2.851505,2.767731,-0.225152,-0.221820,-7.50,-7.50,1.001200,1.00144
42,theta5[2],-1.610920,-1.602370,0.356392,0.339862,0,0,3435.950,3981.580,-0.606374,-0.620254,3.585819,3.533445,-0.757450,-0.751898,-2.50,-2.50,1.001350,1.00090
43,theta5[3],3.417940,3.418940,5.911360,5.920350,0,0,3056.030,3417.400,4.555950,4.558660,3.825740,3.836349,0.752288,0.753331,2.60,2.60,1.002440,1.00122
44,theta6[1],-5.338160,-5.345290,-3.721630,-3.706290,0,0,4288.900,5214.110,-4.498150,-4.497370,1.003703,1.005267,-0.182155,-0.182296,-5.50,-5.50,1.001000,1.00055
45,theta6[2],-2.404090,-2.417940,-1.002860,-0.985839,0,0,4135.470,5145.860,-1.690640,-1.690530,1.018808,1.019030,-0.373837,-0.373878,-2.70,-2.70,1.001270,1.00061
46,theta6[3],3.027490,3.012380,4.588880,4.607330,0,0,4181.040,4685.590,3.783200,3.779380,1.646602,1.636813,0.513280,0.511752,2.50,2.50,1.001790,1.00127
47,theta7[1],-4.064790,-4.076930,-3.264430,-3.265540,0,0,4303.490,4761.410,-3.660120,-3.663360,0.409446,0.405310,-0.148809,-0.148056,-4.30,-4.30,1.000920,0.99990
48,theta7[2],-0.755807,-0.762952,-0.120026,-0.118129,0,0,3300.130,3944.840,-0.438848,-0.441577,0.314892,0.311836,-0.561152,-0.558423,-1.00,-1.00,1.001720,1.00062
49,theta7[3],1.506410,1.511900,2.181770,2.184370,0,0,3547.970,4149.400,1.840690,1.839360,0.194208,0.193037,0.314779,0.313829,1.40,1.40,1.001930,1.00093