In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import os
from math import ceil
from scipy.stats import gaussian_kde
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
import random


try:
    import umap
    HAS_UMAP = True
except ImportError:
    HAS_UMAP = False

In [2]:
def sample_duplicates_test(df):
    grouped = df.groupby("sample_id")
    for name, group in grouped:
        if (len(group) > 1):
            print(f"Sample ID: {name}")
            print(group)
            break  # Just show the first group for brevity

In [3]:
geneticsData = pd.read_csv('../data/GNPC_Harmonized_Dataset_V1/GeneticsV1_anonymized.csv')
geneticsData.head()

  contributor_code                             sample_id  gene  variant
0                R  6cafef94-c7c7-4b94-a2db-001b1e9bc258  APOE       34
1                C  69e4c6ae-4523-4146-aebb-001d13bb5146  APOE       32
2                F  aa2f62aa-c0d3-40f8-9d51-0077c2ff098e  APOE       33
3                Q  ab15806d-4c39-482d-a91c-301972a0c4b5  APOE       44
4                H  968c7201-f58f-41a9-a2b4-00db0c972e19  APOE       33

In [4]:
geneticsData.gene.unique()

array(['APOE', 'C9', 'GRN', 'MAPT', 'C9ORF72', 'ANG', 'FUS', 'SETX',
       'VAPB', 'SOD1', 'VCP', 'TAU', 'TDP43', 'PROGRAN'], dtype=object)

In [5]:
geneticsData.variant.unique()

array([34, 32, 33, 44, 23, -1, 24,  0, 22,  1])

In [6]:
sample_duplicates_test(geneticsData)

Sample ID: 001886bf-3b1f-49cd-a7fc-4a1ec3f765c1
     contributor_code                             sample_id  gene  variant
8328                N  001886bf-3b1f-49cd-a7fc-4a1ec3f765c1  MAPT        0
8329                N  001886bf-3b1f-49cd-a7fc-4a1ec3f765c1    C9        0
8330                N  001886bf-3b1f-49cd-a7fc-4a1ec3f765c1   GRN        0

In [7]:
# sample source data
somaMeta = pd.read_csv('../data/GNPC_Harmonized_Dataset_V1/SomalogicMetaV1_anonymized.csv')
somaMeta.head()

/tmp/ipykernel_649304/3545570142.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  somaMeta = pd.read_csv('../data/GNPC_Harmonized_Dataset_V1/SomalogicMetaV1_anonymized.csv')

,sample_id,contributor_code,visit,plate_id,units,anml_fraction_used_0_005,anml_fraction_used_0_5,anml_fraction_used_20,anml_fraction_used_20_s1,anml_fraction_used_20_s2,...,hyb_control_norm_scale,norm_scale_0_005,norm_scale_0_5,norm_scale_20,norm_scale_20_s1,norm_scale_20_s2,norm_scale_20_s3,row_check,sample_matrix,sample_type
0,8a0e5419-20f3-44d6-bb46-bab165bf8d05,R,1,147,-1,0.866,0.836,0.847,-1.0,-1.0,...,0.934112,1.435652,0.824065,0.722277,-1.0,-1.0,-1.0,PASS,EDTA Plasma,Sample
1,1f2178f2-83a6-46df-aec1-3dd741621068,R,2,147,-1,0.936,0.947,0.954,-1.0,-1.0,...,0.884058,0.894184,0.804804,0.841661,-1.0,-1.0,-1.0,PASS,EDTA Plasma,Sample
2,40c3925c-a770-4adc-9a87-5d9e2a23b855,R,1,147,-1,0.973,0.939,0.913,-1.0,-1.0,...,0.906697,1.100648,1.043171,0.901319,-1.0,-1.0,-1.0,PASS,EDTA Plasma,Sample
3,9de3c941-b32b-4ef8-8d59-6b57b905c657,R,2,147,-1,0.888,0.843,0.859,-1.0,-1.0,...,0.994137,1.165921,0.942466,0.825704,-1.0,-1.0,-1.0,PASS,EDTA Plasma,Sample
4,03830809-3976-4f58-8279-ca2ffd0398c4,R,2,147,-1,0.850,0.828,0.804,-1.0,-1.0,...,0.925489,1.061411,0.659705,0.608147,-1.0,-1.0,-1.0,PASS,EDTA Plasma,Sample

In [8]:
sample_duplicates_test(somaMeta)

In [9]:
# clinical subject data
clinicalData = pd.read_csv('../data/GNPC_Harmonized_Dataset_V1/ClinicalV1_anonymized.csv')
clinicalData.head()

,contributor_code,sample_id,sequential_visit_number,age_at_visit,computed_age_range,sex,race,years_of_education,computed_years_education_range,computed_height_range,...,anxiety,cdr,cognitive_test_date,cognitive_test_score,computed_cognitive_test_score,cognitive_test_battery,computed_clinical_diagnosis,computed_cognitive_impairment,is_neuropath,is_biomarker
0,A,2d5cc071-c66c-4a10-b55b-00d6eb03b6f3,1,69,0,1,5,14,0,0,...,0,-1.0,8/25/2021,30,1,MMSE,-1,0,0,0
1,A,26ac68a0-91e9-4d7e-8b58-00e737c3bcd7,1,76,0,1,5,4,2,0,...,0,-1.0,9/23/2022,23,1,MMSE,1,1,0,0
2,A,28f4a373-ba8e-4832-8485-0158dfd8c62b,1,65,0,2,2,14,0,0,...,1,-1.0,1/13/2022,20,1,MMSE,1,1,0,0
3,A,64b27523-4353-420e-b01a-024c470ccf90,1,65,0,2,2,14,0,0,...,0,-1.0,12/10/2021,26,1,MMSE,2,1,0,0
4,A,b68baa17-b013-412d-bf71-0254b6945e8d,1,73,0,2,2,18,0,0,...,0,-1.0,9/28/2021,27,1,MMSE,-1,0,0,0

In [10]:
sample_duplicates_test(clinicalData)

In [11]:
# clinical subject to sample mapping data
mappingData = pd.read_csv('../data/GNPC_Harmonized_Dataset_V1/PersonMappingV1_anonymized.csv')
mappingData.head()

,person_id,sample_id,is_somalogic,is_mass_spec
0,8aee12c9-962e-48f4-9d15-0008e4443c9d,8aee12c9-962e-48f4-9d15-0008e4443c9d,1,0
1,cd284063-9250-4149-9e8a-0009a615b59d,cd284063-9250-4149-9e8a-0009a615b59d,1,0
2,20fb319a-13a8-4284-83f6-000d1942beb2,20fb319a-13a8-4284-83f6-000d1942beb2,1,0
3,c0493c35-5a4f-4b34-8bdd-000e0c492ae1,c0493c35-5a4f-4b34-8bdd-000e0c492ae1,1,0
4,c0493c35-5a4f-4b34-8bdd-000e0c492ae1,7cdd93db-f393-4a53-a9cb-7cd67ef4b60b,1,0

In [12]:
sample_duplicates_test(mappingData)

In [13]:
# Separate different sample matrices into different dataframes
somaGroups = {key: subdf for key, subdf in somaMeta.groupby("sample_matrix")}
plasmaSoma = somaGroups["EDTA Plasma"]
plasmaSoma.head()

,sample_id,contributor_code,visit,plate_id,units,anml_fraction_used_0_005,anml_fraction_used_0_5,anml_fraction_used_20,anml_fraction_used_20_s1,anml_fraction_used_20_s2,...,hyb_control_norm_scale,norm_scale_0_005,norm_scale_0_5,norm_scale_20,norm_scale_20_s1,norm_scale_20_s2,norm_scale_20_s3,row_check,sample_matrix,sample_type
0,8a0e5419-20f3-44d6-bb46-bab165bf8d05,R,1,147,-1,0.866,0.836,0.847,-1.0,-1.0,...,0.934112,1.435652,0.824065,0.722277,-1.0,-1.0,-1.0,PASS,EDTA Plasma,Sample
1,1f2178f2-83a6-46df-aec1-3dd741621068,R,2,147,-1,0.936,0.947,0.954,-1.0,-1.0,...,0.884058,0.894184,0.804804,0.841661,-1.0,-1.0,-1.0,PASS,EDTA Plasma,Sample
2,40c3925c-a770-4adc-9a87-5d9e2a23b855,R,1,147,-1,0.973,0.939,0.913,-1.0,-1.0,...,0.906697,1.100648,1.043171,0.901319,-1.0,-1.0,-1.0,PASS,EDTA Plasma,Sample
3,9de3c941-b32b-4ef8-8d59-6b57b905c657,R,2,147,-1,0.888,0.843,0.859,-1.0,-1.0,...,0.994137,1.165921,0.942466,0.825704,-1.0,-1.0,-1.0,PASS,EDTA Plasma,Sample
4,03830809-3976-4f58-8279-ca2ffd0398c4,R,2,147,-1,0.850,0.828,0.804,-1.0,-1.0,...,0.925489,1.061411,0.659705,0.608147,-1.0,-1.0,-1.0,PASS,EDTA Plasma,Sample

In [14]:
def merge_left(df1, df2, id_col="sample_id"):
    merged = df1.merge(df2, on=id_col, how="left", suffixes=("", "_dup"))
    dup_cols = [c for c in merged.columns if c.endswith("_dup")]
    return merged.drop(columns=dup_cols)

def merge_meta(selected_meta, mapping, clinicalData):
    merged_with_mapping = merge_left(selected_meta, mapping, id_col="sample_id")
    merged_with_clinical = merge_left(merged_with_mapping, clinicalData, id_col="sample_id")
    
    # Check if the two columns exist
    if "visit" not in merged_with_clinical.columns or "sequential_visit_number" not in merged_with_clinical.columns:
        pass

    # Check if values are identical
    elif (merged_with_clinical["visit"] == merged_with_clinical["sequential_visit_number"]).all():
        # Drop sequential_visit_number if identical
        merged_with_clinical = merged_with_clinical.drop(columns=["sequential_visit_number"])
        print("Dropped 'sequential_visit_number' because it is identical to 'visit'.")
    else:
        # Raise error if they differ
        mismatched_rows = merged_with_clinical[merged_with_clinical["visit"] != merged_with_clinical["sequential_visit_number"]]
        raise ValueError(
            f"'visit' and 'sequential_visit_number' differ in {len(mismatched_rows)} rows."
        )
    return merged_with_clinical
plasmaSomaMerged = merge_meta(plasmaSoma, mappingData, clinicalData)
plasmaSomaMerged.head()

Dropped 'sequential_visit_number' because it is identical to 'visit'.

,sample_id,contributor_code,visit,plate_id,units,anml_fraction_used_0_005,anml_fraction_used_0_5,anml_fraction_used_20,anml_fraction_used_20_s1,anml_fraction_used_20_s2,...,anxiety,cdr,cognitive_test_date,cognitive_test_score,computed_cognitive_test_score,cognitive_test_battery,computed_clinical_diagnosis,computed_cognitive_impairment,is_neuropath,is_biomarker
0,8a0e5419-20f3-44d6-bb46-bab165bf8d05,R,1,147,-1,0.866,0.836,0.847,-1.0,-1.0,...,-1,-1.0,1/1/1900,28,1,MMSE,-1,0,1,0
1,1f2178f2-83a6-46df-aec1-3dd741621068,R,2,147,-1,0.936,0.947,0.954,-1.0,-1.0,...,-1,-1.0,1/1/1900,28,1,MMSE,-1,0,1,0
2,40c3925c-a770-4adc-9a87-5d9e2a23b855,R,1,147,-1,0.973,0.939,0.913,-1.0,-1.0,...,-1,-1.0,1/1/1900,30,1,MMSE,-1,0,1,0
3,9de3c941-b32b-4ef8-8d59-6b57b905c657,R,2,147,-1,0.888,0.843,0.859,-1.0,-1.0,...,-1,-1.0,1/1/1900,28,1,MMSE,-1,0,1,0
4,03830809-3976-4f58-8279-ca2ffd0398c4,R,2,147,-1,0.850,0.828,0.804,-1.0,-1.0,...,-1,-1.0,1/1/1900,28,1,MMSE,-1,0,1,0

In [15]:
def sample_summary(df, cols = None):
    if cols is None:
        cols = ["person_id", "sample_id", "sex", "contributor_code", "sample_type", "visit", "age_at_visit", "ad", "ftd", "pd", "als", "mci_sci", "recruited_control", "cdr", "depression", "anxiety", "cognitive_test_date", "cognitive_test_score", "computed_cognitive_test_score", "cognitive_test_battery", "computed_clinical_diagnosis", "computed_cognitive_impairment", "is_neuropath", "is_biomarker"]
    subdf = df[cols]
    return subdf

plasmaSomaSummary = sample_summary(plasmaSomaMerged)
plasmaSomaSummary.head()

,person_id,sample_id,sex,contributor_code,sample_type,visit,age_at_visit,ad,ftd,pd,...,depression,anxiety,cognitive_test_date,cognitive_test_score,computed_cognitive_test_score,cognitive_test_battery,computed_clinical_diagnosis,computed_cognitive_impairment,is_neuropath,is_biomarker
0,8a0e5419-20f3-44d6-bb46-bab165bf8d05,8a0e5419-20f3-44d6-bb46-bab165bf8d05,2,R,Sample,1,88,0,-1,0,...,-1,-1,1/1/1900,28,1,MMSE,-1,0,1,0
1,a398ecfd-c26b-4e4b-8ca0-9915be6bb958,1f2178f2-83a6-46df-aec1-3dd741621068,1,R,Sample,2,72,0,-1,0,...,-1,-1,1/1/1900,28,1,MMSE,-1,0,1,0
2,40c3925c-a770-4adc-9a87-5d9e2a23b855,40c3925c-a770-4adc-9a87-5d9e2a23b855,2,R,Sample,1,77,0,-1,0,...,-1,-1,1/1/1900,30,1,MMSE,-1,0,1,0
3,8a0e5419-20f3-44d6-bb46-bab165bf8d05,9de3c941-b32b-4ef8-8d59-6b57b905c657,2,R,Sample,2,90,0,-1,0,...,-1,-1,1/1/1900,28,1,MMSE,-1,0,1,0
4,92c1caea-95f8-4740-a038-04a85f106b62,03830809-3976-4f58-8279-ca2ffd0398c4,2,R,Sample,2,90,0,-1,0,...,-1,-1,1/1/1900,28,1,MMSE,-1,0,1,0

In [16]:
def clean_stage_noise(pf, stage_cols):
    sorted_pf = pf.sort_values(by="visit")
    for stage_col in stage_cols:
        # get rid of 0 and -1 after 1
        first_confirmed_cu = 0
        first_confirmed_ci = 0
        if 1 in sorted_pf[stage_col].values:
            first_confirmed_ci = sorted_pf.loc[sorted_pf[stage_col] == 1, "visit"].iloc[0]
            sorted_pf.loc[sorted_pf["visit"] > first_confirmed_ci, stage_col] = 1
        # get rid of -1 before 0
        if 0 in sorted_pf[stage_col].values:
            first_confirmed_cu = sorted_pf.loc[sorted_pf[stage_col] == 0, "visit"].iloc[0]
            sorted_pf.loc[sorted_pf["visit"] < first_confirmed_cu, stage_col] = 0
        if first_confirmed_cu < first_confirmed_ci:
            sorted_pf.loc[(sorted_pf["visit"] > first_confirmed_cu) & (sorted_pf["visit"] < first_confirmed_ci), stage_col] = 0

    return sorted_pf

In [17]:
def converter_check(pdf):
    converter_status = None
    person_df = clean_stage_noise(pdf, stage_cols=['mci_sci', 'ad'])

    mci_vals = person_df['mci_sci'].unique()
    ad_vals = person_df['ad'].unique()

    if 0 in mci_vals and 1 in mci_vals and 0 in ad_vals and 1 in ad_vals:
        converter_status = "cu2mci2ad"
    elif 0 in mci_vals and 1 in mci_vals and 1 not in ad_vals:
        converter_status = "cu2mci"
    elif 0 in ad_vals and 1 in ad_vals:
        converter_status = "mci2ad"
    elif (1 in mci_vals and 0 not in mci_vals and 1 not in ad_vals):
        converter_status = "mci"
    elif (1 in ad_vals and 0 not in ad_vals):
        converter_status = "ad"
    else:
        converter_status = "cu"
    return converter_status

In [18]:
def other_nd_check(person_df, nd_type):
    nd_status = None
    nd_vals = person_df[nd_type].unique()

    if 0 in nd_vals and 1 in nd_vals:
        nd_status = f"cu2{nd_type}"
    elif (1 in nd_vals and 0 not in nd_vals):
        nd_status = nd_type
    else:
        nd_status = "cu"
    return nd_status

In [19]:
def continuous_summary(patients, disease_stage, person_dfs, metric):
    dfs = [person_dfs.get_group(pid) for pid in patients[disease_stage][-1] + patients[disease_stage][1] + patients[disease_stage][2]]
    combined_df = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    if combined_df.empty:
        return {stage: {} for stage in disease_stage.split("2")}
    stages = disease_stage.split("2")
    summary = {}
    for stage in stages:
        if stage == "cu":
            stage_df = combined_df[(combined_df['ad'] == 0) & (combined_df['mci_sci'] == 0)]
        elif stage == "mci":
            stage_df = combined_df[(combined_df['mci_sci'] == 1) & (combined_df['ad'] == 0)]
        elif stage == "ad":
            stage_df = combined_df[combined_df['ad'] == 1]
        
        if metric == "cognitive_test_score":
            # metric_counts = stage_df.loc[stage_df[metric].between(0, 30), metric].describe().to_dict()
            df = stage_df.loc[stage_df[metric].between(0, 30)].copy()
            if df.empty:
                weighted_mean = np.nan
                weighted_std = np.nan
            else:
                df['weight'] = (
                    1 / df.groupby('person_id')[metric].transform('count')
                )

                weighted_mean = np.average(df[metric], weights=df['weight'])
                weighted_var = np.average(
                    (df[metric] - weighted_mean)**2,
                    weights=df['weight']
                )
                weighted_std = np.sqrt(weighted_var)
        else:
            raise ValueError(f"Unsupported continuous metric: {metric}")
        # summary[stage] = metric_counts
        summary[stage] = {
            'weighted_mean': weighted_mean,
            'weighted_std': weighted_std
        }
    return summary

In [20]:
def discrete_status_approximate(pf, status_cols):
    for stage in ["cu", "mci", "ad"]:
        for status_col in status_cols:
            if stage == "cu":
                stage_df = pf[(pf['ad'] == 0) & (pf['mci_sci'] == 0)]
            elif stage == "mci":
                stage_df = pf[(pf['mci_sci'] == 1) & (pf['ad'] == 0)]
            elif stage == "ad":
                stage_df = pf[pf['ad'] == 1]
        first_confirmed_cu = 0
        first_confirmed_ci = 0
        if 1 in pf[status_col].values:
            first_confirmed_ci = pf.loc[pf[status_col] == 1, "visit"].iloc[0]
            pf.loc[pf["visit"] > first_confirmed_ci, status_col] = 1
        # get rid of -1 before 0
        if 0 in pf[status_col].values:
            first_confirmed_cu = pf.loc[pf[status_col] == 0, "visit"].iloc[0]
            pf.loc[pf["visit"] < first_confirmed_cu, status_col] = 0
        if first_confirmed_cu < first_confirmed_ci:
            pf.loc[(pf["visit"] > first_confirmed_cu) & (pf["visit"] < first_confirmed_ci), status_col] = 0

    return pf

In [21]:
def discrete_summary(patients, disease_stage, person_dfs, metric):
    dfs = [person_dfs.get_group(pid) for pid in patients[disease_stage][-1] + patients[disease_stage][1] + patients[disease_stage][2]]
    combined_df = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    if combined_df.empty:
        return {stage: {} for stage in disease_stage.split("2")}
    stages = disease_stage.split("2")
    summary = {}
    for stage in stages:
        if stage == "cu":
            stage_df = combined_df[(combined_df['ad'] == 0) & (combined_df['mci_sci'] == 0)]
        elif stage == "mci":
            stage_df = combined_df[(combined_df['mci_sci'] == 1) & (combined_df['ad'] == 0)]
        elif stage == "ad":
            stage_df = combined_df[combined_df['ad'] == 1]
        
        metric_counts = dict.fromkeys(stage_df[metric].unique(), 0)
        for pid in stage_df['person_id'].unique():
            person_df = stage_df[stage_df['person_id'] == pid]
            vals = person_df[metric].unique()
            for val in vals:
                metric_counts[val] += 1
        summary[stage] = metric_counts
    return summary

In [22]:
def genetic_summary(patients, disease_stage, person_dfs, geneticsData):
    dfs = [person_dfs.get_group(pid) for pid in patients[disease_stage][-1] + patients[disease_stage][1] + patients[disease_stage][2]]
    combined_df = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()
    if combined_df.empty:
        return {stage: {} for stage in disease_stage.split("2")}
    stages = disease_stage.split("2")
    summary = {}
    for stage in stages:
        if stage == "cu":
            stage_df = combined_df[(combined_df['ad'] == 0) & (combined_df['mci_sci'] == 0)]
        elif stage == "mci":
            stage_df = combined_df[(combined_df['mci_sci'] == 1) & (combined_df['ad'] == 0)]
        elif stage == "ad":
            stage_df = combined_df[combined_df['ad'] == 1]
        summary[stage] = {}
        for _, row in stage_df.iterrows():
            person_id = row['person_id']
            sample_id = row['sample_id']
            sample_genetics = geneticsData[geneticsData['sample_id'] == sample_id]
            for _, gene_row in sample_genetics.iterrows():
                gene = gene_row['gene']
                variant = gene_row['variant']
                if gene in summary[stage]:
                    if variant in summary[stage][gene]:
                        summary[stage][gene][variant].add(person_id)
                    else:
                        summary[stage][gene][variant] = set([person_id])
                else:
                    summary[stage][gene] = {variant: set([person_id])}
        
    return summary

In [23]:
def cohort_summary(df, cohort, geneticsData):
    grouped = df.groupby("contributor_code")
    cohort_df = grouped.get_group(cohort)
    person_dfs = cohort_df.groupby("person_id")
    nd_types = ["pd", "ftd", "als"]
    discrete_metrics = ["depression", "anxiety", "cdr", "computed_cognitive_test_score"]
    continuous_metrics = ["cognitive_test_score"]


    single_visit_converter_patients = {"cu": {-1: [], 1: [], 2: []}, "mci": {-1: [], 1: [], 2: []}, "ad": {-1: [], 1: [], 2: []}}
    single_visit_other_nd_patients = {"pd": {-1: [], 1: [], 2: []}, "ftd": {-1: [], 1: [], 2: []}, "als": {-1: [], 1: [], 2: []}}
    multi_visit_converter_patients = {"cu": {-1: [], 1: [], 2: []}, "mci": {-1: [], 1: [], 2: []}, "ad": {-1: [], 1: [], 2: []}, "cu2mci": {-1: [], 1: [], 2: []}, "mci2ad": {-1: [], 1: [], 2: []}, "cu2ad": {-1: [], 1: [], 2: []}, "cu2mci2ad": {-1: [], 1: [], 2: []}}
    multi_visit_other_nd_patients = {"pd": {-1: [], 1: [], 2: []}, "ftd": {-1: [], 1: [], 2: []}, "als": {-1: [], 1: [], 2: []}, "cu2pd": {-1: [], 1: [], 2: []}, "cu2ftd": {-1: [], 1: [], 2: []}, "cu2als": {-1: [], 1: [], 2: []}}

    for person_id, person_df in person_dfs:
        visits = person_df['visit'].nunique()
        record_count = len(person_df)
        conv_state = converter_check(person_df)
        if (record_count != visits):
            print(f"Data inconsistency for person_id {person_id}: {record_count} records but {visits} unique visits.")
        if record_count == 1:
            single_visit_converter_patients[conv_state][person_df['sex'].iloc[0]].append(person_id)
            for nd in nd_types:
                nd_state = other_nd_check(person_df, nd)
                if nd_state != "cu":
                    single_visit_other_nd_patients[nd_state][person_df['sex'].iloc[0]].append(person_id)
        else:
            multi_visit_converter_patients[conv_state][person_df['sex'].iloc[0]].append(person_id)
            for nd in nd_types:
                nd_state = other_nd_check(person_df, nd)
                if nd_state != "cu":
                    multi_visit_other_nd_patients[nd_state][person_df['sex'].iloc[0]].append(person_id)
    
    print(f"Cohort: {cohort}")
    for state, stats in single_visit_converter_patients.items():
        print(f"Single-visit converter patients:\n {state}:\n male : {len(stats[1])}, female: {len(stats[2])}, unknown: {len(stats[-1])}, total: {len(stats[1]) + len(stats[2]) + len(stats[-1])}")

    for state, stats in multi_visit_converter_patients.items():
        print(f"Multiple-visit converter patients:\n {state}:\n male : {len(stats[1])}, female: {len(stats[2])}, unknown: {len(stats[-1])}, total: {len(stats[1]) + len(stats[2]) + len(stats[-1])}")

    for ad_state, ad_stats in single_visit_converter_patients.items():
        for nd_state, nd_stats in single_visit_other_nd_patients.items():
            print(f"Single-visit patients:\n Converter state: {ad_state}, Other ND state: {nd_state}:\n male : {len(set(ad_stats[1]) & set(nd_stats[1]))}, female: {len(set(ad_stats[2]) & set(nd_stats[2]))}, unknown: {len(set(ad_stats[-1]) & set(nd_stats[-1]))}, total: {len(set(ad_stats[1]) & set(nd_stats[1])) + len(set(ad_stats[2]) & set(nd_stats[2])) + len(set(ad_stats[-1]) & set(nd_stats[-1]))}")
    
    for ad_state, ad_stats in multi_visit_converter_patients.items():
        for nd_state, nd_stats in multi_visit_other_nd_patients.items():
            print(f"Multiple-visit patients:\n Converter state: {ad_state}, Other ND state: {nd_state}:\n male : {len(set(ad_stats[1]) & set(nd_stats[1]))}, female: {len(set(ad_stats[2]) & set(nd_stats[2]))}, unknown: {len(set(ad_stats[-1]) & set(nd_stats[-1]))}, total: {len(set(ad_stats[1]) & set(nd_stats[1])) + len(set(ad_stats[2]) & set(nd_stats[2])) + len(set(ad_stats[-1]) & set(nd_stats[-1]))}")
    
    for metric in discrete_metrics:
        for stage in single_visit_converter_patients.keys():
            summary = discrete_summary(single_visit_converter_patients, stage, person_dfs, metric)
            print(f"Single-visit patients - Discrete metric '{metric}' summary for stage '{stage}': {summary}")
        for stage in multi_visit_converter_patients.keys():
            summary = discrete_summary(multi_visit_converter_patients, stage, person_dfs, metric)
            print(f"Multiple-visit patients - Discrete metric '{metric}' summary for stage '{stage}': {summary}")
    
    for metric in continuous_metrics:
        for stage in single_visit_converter_patients.keys():
            summary = continuous_summary(single_visit_converter_patients, stage, person_dfs, metric)
            print(f"Single-visit patients - Continuous metric '{metric}' summary for stage '{stage}': {summary}")
        for stage in multi_visit_converter_patients.keys():
            summary = continuous_summary(multi_visit_converter_patients, stage, person_dfs, metric)
            print(f"Multiple-visit patients - Continuous metric '{metric}' summary for stage '{stage}': {summary}")
    
    for stage in single_visit_converter_patients.keys():
        summary = genetic_summary(single_visit_converter_patients, stage, person_dfs, geneticsData)
        print(f"Single-visit patients - Genetic summary for stage '{stage}':")
        for substage, gene_data in summary.items():
            print(f"  Stage: {substage}")
            for gene, variants in gene_data.items():
                for variant, persons in variants.items():
                    print(f"    Gene: {gene}, Variant: {variant}, Count: {len(persons)}")

    for stage in multi_visit_converter_patients.keys():
        summary = genetic_summary(multi_visit_converter_patients, stage, person_dfs, geneticsData)
        print(f"Multiple-visit patients - Genetic summary for stage '{stage}':")
        for substage, gene_data in summary.items():
            print(f"  Stage: {substage}")
            for gene, variants in gene_data.items():
                for variant, persons in variants.items():
                    print(f"    Gene: {gene}, Variant: {variant}, Count: {len(persons)}")
    return single_visit_converter_patients, single_visit_other_nd_patients, multi_visit_converter_patients, multi_visit_other_nd_patients

In [24]:
for cohort in ["B", "D", "F", "I", "J", "P", "R"]:
    cohort_summary(plasmaSomaSummary, cohort, geneticsData)

Cohort: B
Single-visit converter patients:
 cu:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit converter patients:
 mci:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit converter patients:
 ad:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit converter patients:
 cu:
 male : 101, female: 143, unknown: 0, total: 244
Multiple-visit converter patients:
 mci:
 male : 37, female: 48, unknown: 0, total: 85
Multiple-visit converter patients:
 ad:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit converter patients:
 cu2mci:
 male : 38, female: 76, unknown: 0, total: 114
Multiple-visit converter patients:
 mci2ad:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit converter patients:
 cu2ad:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit converter patients:
 cu2mci2ad:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: cu, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: cu, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: cu, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: mci, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: mci, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: mci, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: ad, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: ad, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: ad, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu, Other ND state: cu2pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu, Other ND state: cu2ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu, Other ND state: cu2als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci, Other ND state: cu2pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci, Other ND state: cu2ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci, Other ND state: cu2als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: ad, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: ad, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: ad, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: ad, Other ND state: cu2pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: ad, Other ND state: cu2ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: ad, Other ND state: cu2als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci, Other ND state: cu2pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci, Other ND state: cu2ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci, Other ND state: cu2als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci2ad, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci2ad, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci2ad, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci2ad, Other ND state: cu2pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci2ad, Other ND state: cu2ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci2ad, Other ND state: cu2als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2ad, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2ad, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2ad, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2ad, Other ND state: cu2pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2ad, Other ND state: cu2ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2ad, Other ND state: cu2als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci2ad, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci2ad, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci2ad, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci2ad, Other ND state: cu2pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci2ad, Other ND state: cu2ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci2ad, Other ND state: cu2als:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients - Discrete metric 'depression' summary for stage 'cu': {'cu': {}}
Single-visit patients - Discrete metric 'depression' summary for stage 'mci': {'mci': {}}
Single-visit patients - Discrete metric 'depression' summary for stage 'ad': {'ad': {}}
Multiple-visit patients - Discrete metric 'depression' summary for stage 'cu': {'cu': {np.int64(0): 227, np.int64(1): 48, np.int64(2): 14, np.int64(-1): 8}}
Multiple-visit patients - Discrete metric 'depression' summary for stage 'mci': {'mci': {np.int64(0): 63, np.int64(2): 5, np.int64(1): 28, np.int64(-1): 2}}
Multiple-visit patients - Discrete metric 'depression' summary for stage 'ad': {'ad': {}}
Multiple-visit patients - Discrete metric 'depression' summary for stage 'cu2mci': {'cu': {np.int64(0): 95, np.int64(1): 24, np.int64(2): 6, np.int64(-1): 2}, 'mci': {np.int64(0): 83, np.int64(1): 31, np.int64(-1): 2, np.int64(2): 5}}
Multiple-visit patients - Discrete metric 'depression' summary for stage 'mci2ad': {'mci': {}, 'ad': {}}
Multiple-visit patients - Discrete metric 'depression' summary for stage 'cu2ad': {'cu': {}, 'ad': {}}
Multiple-visit patients - Discrete metric 'depression' summary for stage 'cu2mci2ad': {'cu': {}, 'mci': {}, 'ad': {}}
Single-visit patients - Discrete metric 'anxiety' summary for stage 'cu': {'cu': {}}
Single-visit patients - Discrete metric 'anxiety' summary for stage 'mci': {'mci': {}}
Single-visit patients - Discrete metric 'anxiety' summary for stage 'ad': {'ad': {}}
Multiple-visit patients - Discrete metric 'anxiety' summary for stage 'cu': {'cu': {np.int64(0): 239, np.int64(1): 36, np.int64(2): 19, np.int64(-1): 15}}
Multiple-visit patients - Discrete metric 'anxiety' summary for stage 'mci': {'mci': {np.int64(0): 77, np.int64(2): 8, np.int64(1): 13, np.int64(-1): 5}}
Multiple-visit patients - Discrete metric 'anxiety' summary for stage 'ad': {'ad': {}}
Multiple-visit patients - Discrete metric 'anxiety' summary for stage 'cu2mci': {'cu': {np.int64(1): 12, np.int64(0): 105, np.int64(2): 6, np.int64(-1): 2}, 'mci': {np.int64(-1): 4, np.int64(1): 20, np.int64(0): 92, np.int64(2): 7}}
Multiple-visit patients - Discrete metric 'anxiety' summary for stage 'mci2ad': {'mci': {}, 'ad': {}}
Multiple-visit patients - Discrete metric 'anxiety' summary for stage 'cu2ad': {'cu': {}, 'ad': {}}
Multiple-visit patients - Discrete metric 'anxiety' summary for stage 'cu2mci2ad': {'cu': {}, 'mci': {}, 'ad': {}}
Single-visit patients - Discrete metric 'cdr' summary for stage 'cu': {'cu': {}}
Single-visit patients - Discrete metric 'cdr' summary for stage 'mci': {'mci': {}}
Single-visit patients - Discrete metric 'cdr' summary for stage 'ad': {'ad': {}}
Multiple-visit patients - Discrete metric 'cdr' summary for stage 'cu': {'cu': {np.float64(0.0): 244, np.float64(-1.0): 1}}
Multiple-visit patients - Discrete metric 'cdr' summary for stage 'mci': {'mci': {np.float64(0.0): 85, np.float64(0.5): 5}}
Multiple-visit patients - Discrete metric 'cdr' summary for stage 'ad': {'ad': {}}
Multiple-visit patients - Discrete metric 'cdr' summary for stage 'cu2mci': {'cu': {np.float64(0.0): 114, np.float64(0.5): 1}, 'mci': {np.float64(0.0): 112, np.float64(0.5): 5}}
Multiple-visit patients - Discrete metric 'cdr' summary for stage 'mci2ad': {'mci': {}, 'ad': {}}
Multiple-visit patients - Discrete metric 'cdr' summary for stage 'cu2ad': {'cu': {}, 'ad': {}}
Multiple-visit patients - Discrete metric 'cdr' summary for stage 'cu2mci2ad': {'cu': {}, 'mci': {}, 'ad': {}}
Single-visit patients - Discrete metric 'computed_cognitive_test_score' summary for stage 'cu': {'cu': {}}
Single-visit patients - Discrete metric 'computed_cognitive_test_score' summary for stage 'mci': {'mci': {}}
Single-visit patients - Discrete metric 'computed_cognitive_test_score' summary for stage 'ad': {'ad': {}}
Multiple-visit patients - Discrete metric 'computed_cognitive_test_score' summary for stage 'cu': {'cu': {np.int64(1): 244}}
Multiple-visit patients - Discrete metric 'computed_cognitive_test_score' summary for stage 'mci': {'mci': {np.int64(1): 85}}
Multiple-visit patients - Discrete metric 'computed_cognitive_test_score' summary for stage 'ad': {'ad': {}}
Multiple-visit patients - Discrete metric 'computed_cognitive_test_score' summary for stage 'cu2mci': {'cu': {np.int64(1): 114}, 'mci': {np.int64(1): 114, np.int64(-1): 1}}
Multiple-visit patients - Discrete metric 'computed_cognitive_test_score' summary for stage 'mci2ad': {'mci': {}, 'ad': {}}
Multiple-visit patients - Discrete metric 'computed_cognitive_test_score' summary for stage 'cu2ad': {'cu': {}, 'ad': {}}
Multiple-visit patients - Discrete metric 'computed_cognitive_test_score' summary for stage 'cu2mci2ad': {'cu': {}, 'mci': {}, 'ad': {}}
Single-visit patients - Continuous metric 'cognitive_test_score' summary for stage 'cu': {'cu': {}}
Single-visit patients - Continuous metric 'cognitive_test_score' summary for stage 'mci': {'mci': {}}
Single-visit patients - Continuous metric 'cognitive_test_score' summary for stage 'ad': {'ad': {}}
Multiple-visit patients - Continuous metric 'cognitive_test_score' summary for stage 'cu': {'cu': {'weighted_mean': np.float64(29.185792349726775), 'weighted_std': np.float64(0.982589030461364)}}
Multiple-visit patients - Continuous metric 'cognitive_test_score' summary for stage 'mci': {'mci': {'weighted_mean': np.float64(29.15098039215686), 'weighted_std': np.float64(1.0072039630307976)}}
Multiple-visit patients - Continuous metric 'cognitive_test_score' summary for stage 'ad': {'ad': {}}
Multiple-visit patients - Continuous metric 'cognitive_test_score' summary for stage 'cu2mci': {'cu': {'weighted_mean': np.float64(28.903508771929825), 'weighted_std': np.float64(1.1314429402829096)}, 'mci': {'weighted_mean': np.float64(29.035087719298247), 'weighted_std': np.float64(1.103660771056253)}}
Multiple-visit patients - Continuous metric 'cognitive_test_score' summary for stage 'mci2ad': {'mci': {}, 'ad': {}}
Multiple-visit patients - Continuous metric 'cognitive_test_score' summary for stage 'cu2ad': {'cu': {}, 'ad': {}}
Multiple-visit patients - Continuous metric 'cognitive_test_score' summary for stage 'cu2mci2ad': {'cu': {}, 'mci': {}, 'ad': {}}
Single-visit patients - Genetic summary for stage 'cu':
  Stage: cu
Single-visit patients - Genetic summary for stage 'mci':
  Stage: mci
Single-visit patients - Genetic summary for stage 'ad':
  Stage: ad
Multiple-visit patients - Genetic summary for stage 'cu':
  Stage: cu
    Gene: APOE, Variant: 34, Count: 102
    Gene: APOE, Variant: 33, Count: 99
    Gene: APOE, Variant: 23, Count: 16
    Gene: APOE, Variant: 44, Count: 26
    Gene: APOE, Variant: 24, Count: 1
Multiple-visit patients - Genetic summary for stage 'mci':
  Stage: mci
    Gene: APOE, Variant: 33, Count: 32
    Gene: APOE, Variant: 34, Count: 37
    Gene: APOE, Variant: 24, Count: 6
    Gene: APOE, Variant: 44, Count: 7
    Gene: APOE, Variant: 23, Count: 3
Multiple-visit patients - Genetic summary for stage 'ad':
  Stage: ad
Multiple-visit patients - Genetic summary for stage 'cu2mci':
  Stage: cu
    Gene: APOE, Variant: 33, Count: 40
    Gene: APOE, Variant: 34, Count: 55
    Gene: APOE, Variant: 24, Count: 3
    Gene: APOE, Variant: 23, Count: 9
    Gene: APOE, Variant: 44, Count: 7
  Stage: mci
    Gene: APOE, Variant: 33, Count: 40
    Gene: APOE, Variant: 34, Count: 55
    Gene: APOE, Variant: 24, Count: 3
    Gene: APOE, Variant: 23, Count: 9
    Gene: APOE, Variant: 44, Count: 7
Multiple-visit patients - Genetic summary for stage 'mci2ad':
  Stage: mci
  Stage: ad
Multiple-visit patients - Genetic summary for stage 'cu2ad':
  Stage: cu
  Stage: ad
Multiple-visit patients - Genetic summary for stage 'cu2mci2ad':
  Stage: cu
  Stage: mci
  Stage: ad
Cohort: D
Single-visit converter patients:
 cu:
 male : 14, female: 35, unknown: 0, total: 49
Single-visit converter patients:
 mci:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit converter patients:
 ad:
 male : 74, female: 112, unknown: 0, total: 186
Multiple-visit converter patients:
 cu:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit converter patients:
 mci:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit converter patients:
 ad:
 male : 82, female: 99, unknown: 0, total: 181
Multiple-visit converter patients:
 cu2mci:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit converter patients:
 mci2ad:
 male : 22, female: 45, unknown: 0, total: 67
Multiple-visit converter patients:
 cu2ad:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit converter patients:
 cu2mci2ad:
 male : 3, female: 3, unknown: 0, total: 6
Single-visit patients:
 Converter state: cu, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: cu, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: cu, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: mci, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: mci, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: mci, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: ad, Other ND state: pd:
 male : 2, female: 0, unknown: 0, total: 2
Single-visit patients:
 Converter state: ad, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: ad, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu, Other ND state: cu2pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu, Other ND state: cu2ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu, Other ND state: cu2als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci, Other ND state: cu2pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci, Other ND state: cu2ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci, Other ND state: cu2als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: ad, Other ND state: pd:
 male : 1, female: 0, unknown: 0, total: 1
Multiple-visit patients:
 Converter state: ad, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: ad, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: ad, Other ND state: cu2pd:
 male : 0, female: 1, unknown: 0, total: 1
Multiple-visit patients:
 Converter state: ad, Other ND state: cu2ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: ad, Other ND state: cu2als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci, Other ND state: cu2pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci, Other ND state: cu2ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci, Other ND state: cu2als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci2ad, Other ND state: pd:
 male : 2, female: 0, unknown: 0, total: 2
Multiple-visit patients:
 Converter state: mci2ad, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci2ad, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci2ad, Other ND state: cu2pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci2ad, Other ND state: cu2ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci2ad, Other ND state: cu2als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2ad, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2ad, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2ad, Other ND state: als:

In [25]:
rlt = cohort_summary(plasmaSomaSummary, "P", geneticsData)

Cohort: P
Single-visit converter patients:
 cu:
 male : 12, female: 3, unknown: 0, total: 15
Single-visit converter patients:
 mci:
 male : 2, female: 1, unknown: 0, total: 3
Single-visit converter patients:
 ad:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit converter patients:
 cu:
 male : 203, female: 185, unknown: 0, total: 388
Multiple-visit converter patients:
 mci:
 male : 16, female: 9, unknown: 0, total: 25
Multiple-visit converter patients:
 ad:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit converter patients:
 cu2mci:
 male : 55, female: 33, unknown: 0, total: 88
Multiple-visit converter patients:
 mci2ad:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit converter patients:
 cu2ad:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit converter patients:
 cu2mci2ad:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: cu, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: cu, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: cu, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: mci, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: mci, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: mci, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: ad, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: ad, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients:
 Converter state: ad, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu, Other ND state: cu2pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu, Other ND state: cu2ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu, Other ND state: cu2als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci, Other ND state: cu2pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci, Other ND state: cu2ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci, Other ND state: cu2als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: ad, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: ad, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: ad, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: ad, Other ND state: cu2pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: ad, Other ND state: cu2ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: ad, Other ND state: cu2als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci, Other ND state: cu2pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci, Other ND state: cu2ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci, Other ND state: cu2als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci2ad, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci2ad, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci2ad, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci2ad, Other ND state: cu2pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci2ad, Other ND state: cu2ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: mci2ad, Other ND state: cu2als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2ad, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2ad, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2ad, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2ad, Other ND state: cu2pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2ad, Other ND state: cu2ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2ad, Other ND state: cu2als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci2ad, Other ND state: pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci2ad, Other ND state: ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci2ad, Other ND state: als:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci2ad, Other ND state: cu2pd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci2ad, Other ND state: cu2ftd:
 male : 0, female: 0, unknown: 0, total: 0
Multiple-visit patients:
 Converter state: cu2mci2ad, Other ND state: cu2als:
 male : 0, female: 0, unknown: 0, total: 0
Single-visit patients - Discrete metric 'depression' summary for stage 'cu': {'cu': {}}
Single-visit patients - Discrete metric 'depression' summary for stage 'mci': {'mci': {}}
Single-visit patients - Discrete metric 'depression' summary for stage 'ad': {'ad': {}}
Multiple-visit patients - Discrete metric 'depression' summary for stage 'cu': {'cu': {}}
Multiple-visit patients - Discrete metric 'depression' summary for stage 'mci': {'mci': {}}
Multiple-visit patients - Discrete metric 'depression' summary for stage 'ad': {'ad': {}}
Multiple-visit patients - Discrete metric 'depression' summary for stage 'cu2mci': {'cu': {}, 'mci': {}}
Multiple-visit patients - Discrete metric 'depression' summary for stage 'mci2ad': {'mci': {}, 'ad': {}}
Multiple-visit patients - Discrete metric 'depression' summary for stage 'cu2ad': {'cu': {}, 'ad': {}}
Multiple-visit patients - Discrete metric 'depression' summary for stage 'cu2mci2ad': {'cu': {}, 'mci': {}, 'ad': {}}
Single-visit patients - Discrete metric 'anxiety' summary for stage 'cu': {'cu': {}}
Single-visit patients - Discrete metric 'anxiety' summary for stage 'mci': {'mci': {}}
Single-visit patients - Discrete metric 'anxiety' summary for stage 'ad': {'ad': {}}
Multiple-visit patients - Discrete metric 'anxiety' summary for stage 'cu': {'cu': {}}
Multiple-visit patients - Discrete metric 'anxiety' summary for stage 'mci': {'mci': {}}
Multiple-visit patients - Discrete metric 'anxiety' summary for stage 'ad': {'ad': {}}
Multiple-visit patients - Discrete metric 'anxiety' summary for stage 'cu2mci': {'cu': {}, 'mci': {}}
Multiple-visit patients - Discrete metric 'anxiety' summary for stage 'mci2ad': {'mci': {}, 'ad': {}}
Multiple-visit patients - Discrete metric 'anxiety' summary for stage 'cu2ad': {'cu': {}, 'ad': {}}
Multiple-visit patients - Discrete metric 'anxiety' summary for stage 'cu2mci2ad': {'cu': {}, 'mci': {}, 'ad': {}}
Single-visit patients - Discrete metric 'cdr' summary for stage 'cu': {'cu': {}}
Single-visit patients - Discrete metric 'cdr' summary for stage 'mci': {'mci': {}}
Single-visit patients - Discrete metric 'cdr' summary for stage 'ad': {'ad': {}}
Multiple-visit patients - Discrete metric 'cdr' summary for stage 'cu': {'cu': {}}
Multiple-visit patients - Discrete metric 'cdr' summary for stage 'mci': {'mci': {}}
Multiple-visit patients - Discrete metric 'cdr' summary for stage 'ad': {'ad': {}}
Multiple-visit patients - Discrete metric 'cdr' summary for stage 'cu2mci': {'cu': {}, 'mci': {}}
Multiple-visit patients - Discrete metric 'cdr' summary for stage 'mci2ad': {'mci': {}, 'ad': {}}
Multiple-visit patients - Discrete metric 'cdr' summary for stage 'cu2ad': {'cu': {}, 'ad': {}}
Multiple-visit patients - Discrete metric 'cdr' summary for stage 'cu2mci2ad': {'cu': {}, 'mci': {}, 'ad': {}}
Single-visit patients - Discrete metric 'computed_cognitive_test_score' summary for stage 'cu': {'cu': {}}
Single-visit patients - Discrete metric 'computed_cognitive_test_score' summary for stage 'mci': {'mci': {}}
Single-visit patients - Discrete metric 'computed_cognitive_test_score' summary for stage 'ad': {'ad': {}}
Multiple-visit patients - Discrete metric 'computed_cognitive_test_score' summary for stage 'cu': {'cu': {}}
Multiple-visit patients - Discrete metric 'computed_cognitive_test_score' summary for stage 'mci': {'mci': {}}
Multiple-visit patients - Discrete metric 'computed_cognitive_test_score' summary for stage 'ad': {'ad': {}}
Multiple-visit patients - Discrete metric 'computed_cognitive_test_score' summary for stage 'cu2mci': {'cu': {}, 'mci': {}}
Multiple-visit patients - Discrete metric 'computed_cognitive_test_score' summary for stage 'mci2ad': {'mci': {}, 'ad': {}}
Multiple-visit patients - Discrete metric 'computed_cognitive_test_score' summary for stage 'cu2ad': {'cu': {}, 'ad': {}}
Multiple-visit patients - Discrete metric 'computed_cognitive_test_score' summary for stage 'cu2mci2ad': {'cu': {}, 'mci': {}, 'ad': {}}
Single-visit patients - Continuous metric 'cognitive_test_score' summary for stage 'cu': {'cu': {'weighted_mean': nan, 'weighted_std': nan}}
Single-visit patients - Continuous metric 'cognitive_test_score' summary for stage 'mci': {'mci': {'weighted_mean': nan, 'weighted_std': nan}}
Single-visit patients - Continuous metric 'cognitive_test_score' summary for stage 'ad': {'ad': {}}
Multiple-visit patients - Continuous metric 'cognitive_test_score' summary for stage 'cu': {'cu': {'weighted_mean': nan, 'weighted_std': nan}}
Multiple-visit patients - Continuous metric 'cognitive_test_score' summary for stage 'mci': {'mci': {'weighted_mean': nan, 'weighted_std': nan}}
Multiple-visit patients - Continuous metric 'cognitive_test_score' summary for stage 'ad': {'ad': {}}
Multiple-visit patients - Continuous metric 'cognitive_test_score' summary for stage 'cu2mci': {'cu': {'weighted_mean': nan, 'weighted_std': nan}, 'mci': {'weighted_mean': nan, 'weighted_std': nan}}
Multiple-visit patients - Continuous metric 'cognitive_test_score' summary for stage 'mci2ad': {'mci': {}, 'ad': {}}
Multiple-visit patients - Continuous metric 'cognitive_test_score' summary for stage 'cu2ad': {'cu': {}, 'ad': {}}
Multiple-visit patients - Continuous metric 'cognitive_test_score' summary for stage 'cu2mci2ad': {'cu': {}, 'mci': {}, 'ad': {}}
Single-visit patients - Genetic summary for stage 'cu':
  Stage: cu
Single-visit patients - Genetic summary for stage 'mci':
  Stage: mci
Single-visit patients - Genetic summary for stage 'ad':
  Stage: ad
Multiple-visit patients - Genetic summary for stage 'cu':
  Stage: cu
Multiple-visit patients - Genetic summary for stage 'mci':
  Stage: mci
Multiple-visit patients - Genetic summary for stage 'ad':
  Stage: ad
Multiple-visit patients - Genetic summary for stage 'cu2mci':
  Stage: cu
  Stage: mci
Multiple-visit patients - Genetic summary for stage 'mci2ad':
  Stage: mci
  Stage: ad
Multiple-visit patients - Genetic summary for stage 'cu2ad':
  Stage: cu
  Stage: ad
Multiple-visit patients - Genetic summary for stage 'cu2mci2ad':
  Stage: cu
  Stage: mci
  Stage: ad

In [26]:
stage_patients = []
for gender, pid in rlt[2]["cu2mci"].items():
    stage_patients.extend(pid)

In [27]:
stage_data = plasmaSomaSummary[plasmaSomaSummary["person_id"].isin(stage_patients)]
patient_level = stage_data.groupby("person_id")
count = 0
for pid, pdf in patient_level:
    count += 1
    print(f"Person ID: {pid}, index: {count}")
    print(pdf[["visit", "mci_sci", "ad", "ftd", "als", "pd", "recruited_control"]].sort_values(by="visit"))

Person ID: 05efe196-294b-44b3-bb34-77aeabc4297c, index: 1
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15996      1        0  -1   -1   -1  -1                  2
15070      2        0  -1   -1   -1  -1                  2
15337      3        0  -1   -1   -1  -1                  2
13865      4        1  -1   -1   -1  -1                  2
Person ID: 06204f24-20be-4939-a8e1-2c9a6d6b4239, index: 2
       visit  mci_sci  ad  ftd  als  pd  recruited_control
17346      1        0  -1   -1   -1  -1                  2
16282      2        0  -1   -1   -1  -1                  2
17347      3        1  -1   -1   -1  -1                  2
Person ID: 0f55b2f8-a793-4dfc-9b7d-da1a71731215, index: 3
       visit  mci_sci  ad  ftd  als  pd  recruited_control
14819      1        0  -1   -1   -1  -1                  2
12194      2        0  -1   -1   -1  -1                  2
15611      3        0  -1   -1   -1  -1                  2
12153      4        1  -1   -1   -1  -1                  2
Person ID: 10a8d365-724f-4fe2-a7b8-cc5c1d50da9b, index: 4
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15317      1        0  -1   -1   -1  -1                  2
16458      2        0  -1   -1   -1  -1                  2
16459      3        1  -1   -1   -1  -1                  2
13849      4        0  -1   -1   -1  -1                  2
Person ID: 11daae44-120d-4708-9139-08bcf2c8022c, index: 5
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16205      1        0  -1   -1   -1  -1                  2
16206      2        0  -1   -1   -1  -1                  2
16058      3        0  -1   -1   -1  -1                  2
16207      4        1  -1   -1   -1  -1                  2
Person ID: 1287a425-7621-4007-a453-d39d901fbc9c, index: 6
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15322      1        0  -1   -1   -1  -1                  2
15047      2        1  -1   -1   -1  -1                  2
13863      3        1  -1   -1   -1  -1                  2
Person ID: 18463816-6aa8-4628-94db-d3125063e49a, index: 7
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16347      1        0  -1   -1   -1  -1                  2
17402      2        0  -1   -1   -1  -1                  2
17403      3        0  -1   -1   -1  -1                  2
17441      4        1  -1   -1   -1  -1                  2
Person ID: 1a077f9a-cfaf-404e-800f-92529e73e123, index: 8
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15453      1        0  -1   -1   -1  -1                  2
15851      2        0  -1   -1   -1  -1                  2
16943      3        1  -1   -1   -1  -1                  2
16944      4        1  -1   -1   -1  -1                  2
Person ID: 1c4dcb56-39c0-4180-9de2-9d917b85a16f, index: 9
       visit  mci_sci  ad  ftd  als  pd  recruited_control
14964      1        0  -1   -1   -1  -1                  2
15236      2        0  -1   -1   -1  -1                  2
15748      3        1  -1   -1   -1  -1                  2
14955      4        0  -1   -1   -1  -1                  2
Person ID: 1f087629-d8e4-4ff7-83b4-16aaf24ecb72, index: 10
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15968      1        0  -1   -1   -1  -1                  2
13934      2        0  -1   -1   -1  -1                  2
13935      3        1  -1   -1   -1  -1                  2
Person ID: 251f3834-7df6-4a30-998a-37e55be44f47, index: 11
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16079      1        0  -1   -1   -1  -1                  2
17294      2        0  -1   -1   -1  -1                  2
16077      3        0  -1   -1   -1  -1                  2
16653      4        1  -1   -1   -1  -1                  2
Person ID: 2ada725b-f0ea-4a3f-a1ea-7a4be0ba324a, index: 12
       visit  mci_sci  ad  ftd  als  pd  recruited_control
12151      1        0  -1   -1   -1  -1                  2
15624      2        1  -1   -1   -1  -1                  2
Person ID: 2c59b02b-7a35-4698-a919-59eec74a84d4, index: 13
       visit  mci_sci  ad  ftd  als  pd  recruited_control
17458      1        0  -1   -1   -1  -1                  2
16345      2        1  -1   -1   -1  -1                  2
Person ID: 306ea1d8-e635-43f7-801f-43c744e27760, index: 14
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16785      1        0  -1   -1   -1  -1                  2
16988      2        0  -1   -1   -1  -1                  2
17434      3        0  -1   -1   -1  -1                  2
16989      4        1  -1   -1   -1  -1                  2
Person ID: 37bc775a-7419-43db-80e9-b0302524cd88, index: 15
       visit  mci_sci  ad  ftd  als  pd  recruited_control
13813      1        0  -1   -1   -1  -1                  2
15025      2        0  -1   -1   -1  -1                  2
13814      3        1  -1   -1   -1  -1                  2
13815      4        1  -1   -1   -1  -1                  2
Person ID: 3ffcc5ca-03c4-4324-a821-f7aa0c5e1dc7, index: 16
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16328      1        0  -1   -1   -1  -1                  2
17391      2        1  -1   -1   -1  -1                  2
Person ID: 420d819e-3f2e-419f-87aa-23666f3a7446, index: 17
       visit  mci_sci  ad  ftd  als  pd  recruited_control
17463      1        0  -1   -1   -1  -1                  2
17464      2        1  -1   -1   -1  -1                  2
17422      3        0  -1   -1   -1  -1                  2
Person ID: 46049426-6543-435f-bf3a-359952446c63, index: 18
       visit  mci_sci  ad  ftd  als  pd  recruited_control
13862      1        0  -1   -1   -1  -1                  2
13859      2        1  -1   -1   -1  -1                  2
Person ID: 48245f07-755e-4db4-abbb-fc511d8ac7e5, index: 19
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16463      1        0  -1   -1   -1  -1                  2
15309      2        0  -1   -1   -1  -1                  2
13850      3        1  -1   -1   -1  -1                  2
Person ID: 4a13057c-cec6-47af-b923-a5568e936121, index: 20
       visit  mci_sci  ad  ftd  als  pd  recruited_control
14518      1        0  -1   -1   -1  -1                  2
14521      2        1  -1   -1   -1  -1                  2
14817      3        0  -1   -1   -1  -1                  2
Person ID: 4bd4b892-18d0-401f-8e4f-3d51d215b8c0, index: 21
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16968      1        0  -1   -1   -1  -1                  2
15872      2        1  -1   -1   -1  -1                  2
Person ID: 4d0120b3-8514-4eb5-83f6-daba8d948e25, index: 22
       visit  mci_sci  ad  ftd  als  pd  recruited_control
18371      1        0  -1   -1   -1  -1                  2
14822      2        1  -1   -1   -1  -1                  2
Person ID: 51b072df-a9a4-4d88-9e61-335712430c88, index: 23
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16254      1        0  -1   -1   -1  -1                  2
16704      2        1  -1   -1   -1  -1                  2
16102      3        1  -1   -1   -1  -1                  2
16261      4        1  -1   -1   -1  -1                  2
16103      5        1  -1   -1   -1  -1                  2
Person ID: 564022fb-4d2e-492b-b5b2-10cf13328077, index: 24
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15797      1        0  -1   -1   -1  -1                  2
13947      2        1  -1   -1   -1  -1                  2
Person ID: 5cf86b3c-66da-41e6-8843-a7d90fc1be06, index: 25
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15808      1        0  -1   -1   -1  -1                  2
16901      2        1  -1   -1   -1  -1                  2
16902      3        1  -1   -1   -1  -1                  2
Person ID: 6c785632-9cb6-4646-be23-350a3237fee6, index: 26
       visit  mci_sci  ad  ftd  als  pd  recruited_control
12210      1        0  -1   -1   -1  -1                  2
14527      2        0  -1   -1   -1  -1                  2
12202      3        0  -1   -1   -1  -1                  2
15629      4        1  -1   -1   -1  -1                  2
Person ID: 6d2febd8-14cc-4e44-aac5-08b57fa563d2, index: 27
       visit  mci_sci  ad  ftd  als  pd  recruited_control
17309      1        0  -1   -1   -1  -1                  2
16092      2        0  -1   -1   -1  -1                  2
16240      3        1  -1   -1   -1  -1                  2
Person ID: 6ee70a5f-1d3a-43a4-b322-52ca5f3ad2fb, index: 28
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15816      1        0  -1   -1   -1  -1                  2
15424      2        1  -1   -1   -1  -1                  2
15990      3        1  -1   -1   -1  -1                  2
Person ID: 705a0068-e621-4d61-ac63-16c2c9a43a55, index: 29
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16703      1        0  -1   -1   -1  -1                  2
16255      2        1  -1   -1   -1  -1                  2
Person ID: 724e3d00-131f-418a-8212-2323c3f12546, index: 30
       visit  mci_sci  ad  ftd  als  pd  recruited_control
17453      1        0  -1   -1   -1  -1                  2
17415      2        1  -1   -1   -1  -1                  2
17419      3        0  -1   -1   -1  -1                  2
Person ID: 7574f6f2-bda0-4793-ad15-54489b5511b8, index: 31
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15861      1        0  -1   -1   -1  -1                  2
16021      2        1  -1   -1   -1  -1                  2
Person ID: 76557832-582d-4753-998d-9e05ba9c5781, index: 32
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15798      1        0  -1   -1   -1  -1                  2
13938      2        0  -1   -1   -1  -1                  2
16905      3        0  -1   -1   -1  -1                  2
15971      4        0  -1   -1   -1  -1                  2
13939      5        1  -1   -1   -1  -1                  2
Person ID: 771e96e9-fce8-4a63-9312-47b5d2c66bc7, index: 33
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16341      1        0  -1   -1   -1  -1                  2
17399      2        1  -1   -1   -1  -1                  2
16340      3        0  -1   -1   -1  -1                  2
Person ID: 7c113dc0-5c21-4355-8689-9c1151387798, index: 34
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16499      1        0  -1   -1   -1  -1                  2
16500      2        1  -1   -1   -1  -1                  2
13884      3        1  -1   -1   -1  -1                  2
16501      4        0  -1   -1   -1  -1                  2
Person ID: 83387713-f27b-477c-aa19-92ead3dfd9fa, index: 35
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16140      1        0  -1   -1   -1  -1                  2
17355      2        1  -1   -1   -1  -1                  2
Person ID: 86b9ec39-455b-40c4-ae62-07d58cb5ac63, index: 36
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16167      1        0  -1   -1   -1  -1                  2
17359      2        1  -1   -1   -1  -1                  2
16735      3        1  -1   -1   -1  -1                  2
Person ID: 8c0d9442-18c5-41ed-833c-146c5415d2a1, index: 37
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16752      1        0  -1   -1   -1  -1                  2
16742      2        1  -1   -1   -1  -1                  2
16743      3        0  -1   -1   -1  -1                  2
Person ID: 91837cd6-e3ba-4a03-9dd3-1454286b4823, index: 38
       visit  mci_sci  ad  ftd  als  pd  recruited_control
17476      1        0  -1   -1   -1  -1                  2
17437      2        1  -1   -1   -1  -1                  2
Person ID: 95bb8da1-f5c5-461c-b112-ad33243ef44c, index: 39
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16791      1        0  -1   -1   -1  -1                  2
15616      2        1  -1   -1   -1  -1                  2
Person ID: 982759f4-1ba3-42d4-b711-3e1c03a6ae48, index: 40
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16662      1        0  -1   -1   -1  -1                  2
16247      2        1  -1   -1   -1  -1                  2
17308      3        1  -1   -1   -1  -1                  2
Person ID: 9999d1e3-738a-4071-bee3-53260389c2e3, index: 41
       visit  mci_sci  ad  ftd  als  pd  recruited_control
12211      1        0  -1   -1   -1  -1                  2
14838      2        0  -1   -1   -1  -1                  2
15639      3        0  -1   -1   -1  -1                  2
15632      4        1  -1   -1   -1  -1                  2
Person ID: 99a93148-0eff-441e-814c-af50a0a55fcb, index: 42
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16919      1        0  -1   -1   -1  -1                  2
15822      2        1  -1   -1   -1  -1                  2
15998      3        1  -1   -1   -1  -1                  2
15821      4        1  -1   -1   -1  -1                  2
Person ID: 9b69abd2-e4be-45bc-8c1a-733c9fba6517, index: 43
       visit  mci_sci  ad  ftd  als  pd  recruited_control
13948      1        0  -1   -1   -1  -1                  2
15800      2        0  -1   -1   -1  -1                  2
13943      3        1  -1   -1   -1  -1                  2
Person ID: 9bedc81c-03d7-49d9-9317-974b615dbdf7, index: 44
       visit  mci_sci  ad  ftd  als  pd  recruited_control
17003      1        0  -1   -1   -1  -1                  2
14520      2        1  -1   -1   -1  -1                  2
17478      3        0  -1   -1   -1  -1                  2
12195      4        0  -1   -1   -1  -1                  2
Person ID: 9c831fa6-399e-43ea-8ace-6764982c2c21, index: 45
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15449      1        0  -1   -1   -1  -1                  2
15434      2        1  -1   -1   -1  -1                  2
Person ID: 9fafdae9-5086-42d9-8350-890e74de36eb, index: 46
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15868      1        0  -1   -1   -1  -1                  2
15479      2        0  -1   -1   -1  -1                  2
15480      3        1  -1   -1   -1  -1                  2
Person ID: a460824f-4ed8-4368-b0e5-6618d540f7d3, index: 47
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16428      1        0  -1   -1   -1  -1                  2
15306      2        1  -1   -1   -1  -1                  2
Person ID: a79b4f98-8c92-4e07-b60d-cea97992960b, index: 48
       visit  mci_sci  ad  ftd  als  pd  recruited_control
14967      1        0  -1   -1   -1  -1                  2
15743      2        0  -1   -1   -1  -1                  2
12334      3        1  -1   -1   -1  -1                  2
Person ID: a7cf05cc-f405-43f7-9ed4-2c2b491bbfe3, index: 49
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16750      1        0  -1   -1   -1  -1                  2
17381      2        1  -1   -1   -1  -1                  2
Person ID: a83f58f9-76a8-4002-9d2a-023f4c633f2a, index: 50
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16191      1        0  -1   -1   -1  -1                  2
17400      2        0  -1   -1   -1  -1                  2
17440      3        1  -1   -1   -1  -1                  2
17401      4        0  -1   -1   -1  -1                  2
Person ID: a88fb565-20d6-4910-83a3-07d461a10db2, index: 51
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15804      1        0  -1   -1   -1  -1                  2
15805      2        0  -1   -1   -1  -1                  2
15806      3        0  -1   -1   -1  -1                  2
15450      4        1  -1   -1   -1  -1                  2
Person ID: ab3eb53e-7a89-4a49-ac74-f1ed149e2fbf, index: 52
       visit  mci_sci  ad  ftd  als  pd  recruited_control
17299      1        0  -1   -1   -1  -1                  2
17300      2        1  -1   -1   -1  -1                  2
16080      3        1  -1   -1   -1  -1                  2
Person ID: abbbaf1a-1d17-4ff9-b37f-85752b1a45e1, index: 53
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15073      1        0  -1   -1   -1  -1                  2
16494      2        1  -1   -1   -1  -1                  2
Person ID: ae1b8217-4500-45ef-9ed4-e639fffbcc31, index: 54
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15491      1        0  -1   -1   -1  -1                  2
16047      2        0  -1   -1   -1  -1                  2
15492      3        0  -1   -1   -1  -1                  2
16055      4        0  -1   -1   -1  -1                  2
16050      5        1  -1   -1   -1  -1                  2
Person ID: b05ee8f2-9ee7-4825-9c36-9a10167aeb75, index: 55
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15728      1        0  -1   -1   -1  -1                  2
13768      2        1  -1   -1   -1  -1                  2
Person ID: b24130ba-3895-4f86-9855-b81fb7fa369b, index: 56
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15419      1        0  -1   -1   -1  -1                  2
16911      2        1  -1   -1   -1  -1                  2
Person ID: b466ae76-8e6b-4e36-9fc8-17d4bb6abd0b, index: 57
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16637      1        0  -1   -1   -1  -1                  2
16638      2        0  -1   -1   -1  -1                  2
15871      3        1  -1   -1   -1  -1                  2
Person ID: b5786e14-498c-4280-99d8-03fec27d950c, index: 58
       visit  mci_sci  ad  ftd  als  pd  recruited_control
14519      1        0  -1   -1   -1  -1                  2
14516      2        0  -1   -1   -1  -1                  2
14818      3        1  -1   -1   -1  -1                  2
Person ID: b67b6eff-6079-4382-991e-d14f85bb0c23, index: 59
       visit  mci_sci  ad  ftd  als  pd  recruited_control
13853      1        0  -1   -1   -1  -1                  2
13854      2        1  -1   -1   -1  -1                  2
Person ID: b6a80141-d746-4468-917f-ee3553088d4f, index: 60
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16652      1        0  -1   -1   -1  -1                  2
16225      2        0  -1   -1   -1  -1                  2
16226      3        1  -1   -1   -1  -1                  2
Person ID: b735a036-c029-444e-8640-677d8c444860, index: 61
       visit  mci_sci  ad  ftd  als  pd  recruited_control
13874      1        0  -1   -1   -1  -1                  2
16488      2        1  -1   -1   -1  -1                  2
15067      3        0  -1   -1   -1  -1                  2
Person ID: b8f1c10f-6e29-45c7-b039-82ffa912374a, index: 62
       visit  mci_sci  ad  ftd  als  pd  recruited_control
12204      1        0  -1   -1   -1  -1                  2
15631      2        0  -1   -1   -1  -1                  2
12216      3        1  -1   -1   -1  -1                  2
15636      4        0  -1   -1   -1  -1                  2
Person ID: b8f98b8e-8845-4a6a-a6ed-ecec5ca38738, index: 63
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16201      1        0  -1   -1   -1  -1                  2
16356      2        0  -1   -1   -1  -1                  2
16775      3        1  -1   -1   -1  -1                  2
16202      4        1  -1   -1   -1  -1                  2
Person ID: c0b34cac-f126-475a-8dcc-7c227b6758f3, index: 64
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16098      1        0  -1   -1   -1  -1                  2
16253      2        1  -1   -1   -1  -1                  2
Person ID: c116f2d2-22a2-43d2-b08d-eaa879a2ad4f, index: 65
       visit  mci_sci  ad  ftd  als  pd  recruited_control
14960      1        0  -1   -1   -1  -1                  2
15734      2        1  -1   -1   -1  -1                  2
15729      3        1  -1   -1   -1  -1                  2
Person ID: c365a5bb-3ea1-4c06-9c18-6a34eb429a8e, index: 66
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16316      1        0  -1   -1   -1  -1                  2
17379      2        1  -1   -1   -1  -1                  2
Person ID: c4076e44-9ed7-454b-939d-93125e1ef2a8, index: 67
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16426      1        0  -1   -1   -1  -1                  2
13816      2        1  -1   -1   -1  -1                  2
Person ID: c59c3943-d900-41cb-b49c-a695c2fe3916, index: 68

In [28]:
cohort_p = pd.read_csv('../data/GNPC_Harmonized_Dataset_V1/contributor_p.csv')
cohort_p.head()

,sample_id,person_id,contributor_code,visit,sample_type,row_check,sample_matrix,ad,ftd,mci_sci,...,EMILIN3_1,ZNF264,ATP4B,DUT,UBXN4_1,IRF6,Status,Diagnosis,Converters,Progression_Simple
0,00683dc0-4d6a-4933-a2c4-0bab1c5be01e,00683dc0-4d6a-4933-a2c4-0bab1c5be01e,P,1,Sample,PASS,EDTA Plasma,-1,-1,0,...,12.338820,10.019591,10.370033,11.907003,14.432633,10.963691,CU,CU,Non-Converter,CU
1,c50241d8-8416-40af-a362-266a4f3c7145,00683dc0-4d6a-4933-a2c4-0bab1c5be01e,P,2,Sample,PASS,EDTA Plasma,-1,-1,0,...,11.697619,10.014439,10.520815,10.080151,12.000247,10.069315,CU,CU,Non-Converter,CU
2,3251f185-b759-4d58-a12b-35158f081011,00683dc0-4d6a-4933-a2c4-0bab1c5be01e,P,3,Sample,PASS,EDTA Plasma,-1,-1,0,...,10.096583,10.295884,10.477455,13.033062,15.248561,11.991593,CU,CU,Non-Converter,CU
3,016e274b-6fe0-436f-a7d0-64a372618828,016e274b-6fe0-436f-a7d0-64a372618828,P,1,Sample,PASS,EDTA Plasma,-1,-1,0,...,9.068510,10.342519,10.529040,13.074292,15.543687,11.966758,CU,CU,Non-Converter,CU
4,3adf0c5c-ec0a-42bb-9304-e53d6782693e,016e274b-6fe0-436f-a7d0-64a372618828,P,2,Sample,FLAG,EDTA Plasma,-1,-1,0,...,9.278682,10.564435,10.558803,13.627944,15.639835,12.571516,CU,CU,Non-Converter,CU

In [29]:
cohort_p["Converters"].unique()

array(['Non-Converter', 'Converter'], dtype=object)

In [56]:
cohort_p["Progression_Simple"].unique()

array(['CU', 'MCI/SCI → Other', 'CU → MCI/SCI', 'Other', 'CU → Other',
       'MCI/SCI', 'CU → MCI/SCI → Other', 'Other → MCI/SCI → Other',
       'MCI/SCI → Other → MCI/SCI', 'Other → MCI/SCI',
       'Other → MCI/SCI → Other → MCI/SCI'], dtype=object)

In [43]:
p1 = list(cohort_p[(cohort_p["Converters"] == "Converter") & (cohort_p["Progression_Simple"] == "CU → MCI/SCI") ]["person_id"].unique())

In [44]:
p2 = list(cohort_p[(cohort_p["Converters"] == "Converter") & (cohort_p["Progression_Simple"] == "CU → MCI/SCI → Other")]["person_id"].unique())

In [46]:
aatman_patients = p1 + p2
aatman_patients = set(aatman_patients)
len(aatman_patients)

81

In [48]:
my_patients = set(stage_patients)
len(my_patients)

88

In [49]:
inter  = aatman_patients & my_patients
len(inter)

81

In [ ]:
addition = my_patients - inter
count = 0
for pid, pdf in patient_level:
    if pid in addition:
        count += 1
        print(f"Person ID: {pid}, index: {count}")
        print(pdf[["visit", "mci_sci", "ad", "ftd", "als", "pd", "recruited_control"]].sort_values(by="visit"))

Person ID: 4a13057c-cec6-47af-b923-a5568e936121, index: 1
       visit  mci_sci  ad  ftd  als  pd  recruited_control
14518      1        0  -1   -1   -1  -1                  2
14521      2        1  -1   -1   -1  -1                  2
14817      3        0  -1   -1   -1  -1                  2
Person ID: ab3eb53e-7a89-4a49-ac74-f1ed149e2fbf, index: 2
       visit  mci_sci  ad  ftd  als  pd  recruited_control
17299      1        0  -1   -1   -1  -1                  2
17300      2        1  -1   -1   -1  -1                  2
16080      3        1  -1   -1   -1  -1                  2
Person ID: cd7f2292-a2bf-4087-a378-1bda40488315, index: 3
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16017      1        0  -1   -1   -1  -1                  2
15442      2        1  -1   -1   -1  -1                  2
Person ID: ed38723a-d3f9-4447-bdd8-b320237f6644, index: 4
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15338      1        0  -1   -1   -1  -1                  2
15061      2        1  -1   -1   -1  -1                  2
16491      3        1  -1   -1   -1  -1                  2
15062      4        1  -1   -1   -1  -1                  2
13866      5        0  -1   -1   -1  -1                  2
Person ID: efb857e8-7e04-4f97-8cb4-f5d76c571ae1, index: 5
       visit  mci_sci  ad  ftd  als  pd  recruited_control
17288      1        0  -1   -1   -1  -1                  2
16646      2        1  -1   -1   -1  -1                  2
17286      3        1  -1   -1   -1  -1                  2
Person ID: f1bbdf85-17ee-4e37-aabe-d2fa17187e05, index: 6
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16019      1        0  -1   -1   -1  -1                  2
16935      2        1  -1   -1   -1  -1                  2
15837      3        0  -1   -1   -1  -1                  2
15441      4        1  -1   -1   -1  -1                  2
16936      5        1  -1   -1   -1  -1                  2
Person ID: fd63a060-040d-4583-bdf6-3934ac3bf063, index: 7
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15304      1        0  -1   -1   -1  -1                  2
16425      2        1  -1   -1   -1  -1                  2
15021      3        1  -1   -1   -1  -1                  2

In [58]:
p3 = list(cohort_p[(cohort_p["Converters"] == "Non-Converter") & (cohort_p["Status"] == "CU") ]["person_id"].unique())
len(p3)

360

In [ ]:
stage_patients3 = []
for gender, pid in rlt[2]["cu"].items():
    stage_patients3.extend(pid)
len(stage_patients3)

388

In [61]:
inter3 = set(p3) & set(stage_patients3)
len(inter3)

360

In [68]:
addition3 = set(stage_patients3) - inter3
stage_data3 = plasmaSomaSummary[plasmaSomaSummary["person_id"].isin(stage_patients3)]
patient_level3 = stage_data3.groupby("person_id")
count = 0
for pid, pdf in patient_level3:
    if pid in addition3:
        count += 1
        print(f"Person ID: {pid}, index: {count}")
        print(pdf[["visit", "mci_sci", "ad", "ftd", "als", "pd", "recruited_control"]].sort_values(by="visit"))

Person ID: 078768db-e696-477a-964c-8e80291d3a17, index: 1
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16951      1        0  -1   -1   -1  -1                  2
15858      2        0  -1   -1   -1  -1                  2
Person ID: 07c7a253-021b-4dfe-aa27-400fe3a1b59e, index: 2
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16083      1        0  -1   -1   -1  -1                  2
16655      2        0  -1   -1   -1  -1                  2
16656      3        0  -1   -1   -1  -1                  2
16084      4        0  -1   -1   -1  -1                  2
Person ID: 36c995ac-16cf-4108-b94d-b66c83742432, index: 3
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16915      1        0  -1   -1   -1  -1                  2
15989      2        0  -1   -1   -1  -1                  2
Person ID: 39f71c3f-4da8-46b5-b438-ed276fdf9663, index: 4
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15463      1        0  -1   -1   -1  -1                  2
15856      2        0  -1   -1   -1  -1                  2
15857      3        0  -1   -1   -1  -1                  2
15464      4        0  -1   -1   -1  -1                  2
Person ID: 3d6b1b59-afda-4e47-afd8-74e3a679efbe, index: 5
       visit  mci_sci  ad  ftd  als  pd  recruited_control
17350      1        0  -1   -1   -1  -1                  2
16714      2        0  -1   -1   -1  -1                  2
Person ID: 580a045c-59c9-43b8-86a9-13c4a45104c7, index: 6
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15796      1        0  -1   -1   -1  -1                  2
16904      2        0  -1   -1   -1  -1                  2
13937      3        0  -1   -1   -1  -1                  2
Person ID: 5b226e3f-bffd-4c12-ad52-0ca14b7723bb, index: 7
       visit  mci_sci  ad  ftd  als  pd  recruited_control
17473      1        0  -1   -1   -1  -1                  2
16782      2        0  -1   -1   -1  -1                  2
Person ID: 5b6a2033-8606-4dd8-948f-8f6734b6025f, index: 8
       visit  mci_sci  ad  ftd  als  pd  recruited_control
14755      1        0  -1   -1   -1  -1                  2
17479      2        0  -1   -1   -1  -1                  2
15557      3        0  -1   -1   -1  -1                  2
Person ID: 62eeac6e-381c-40ca-b8f1-39c8013ad33a, index: 9
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16331      1        0  -1   -1   -1  -1                  2
16768      2        0  -1   -1   -1  -1                  2
16184      3        0  -1   -1   -1  -1                  2
Person ID: 7c7eb3d2-4b9f-4337-83f8-1ac247515be1, index: 10
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15228      1        0  -1   -1   -1  -1                  2
14958      2        0  -1   -1   -1  -1                  2
15238      3        0  -1   -1   -1  -1                  2
Person ID: 87af9ff3-0ff8-4b14-8d3e-378543c65ad7, index: 11
       visit  mci_sci  ad  ftd  als  pd  recruited_control
13810      1        0  -1   -1   -1  -1                  2
15023      2        0  -1   -1   -1  -1                  2
15024      3        0  -1   -1   -1  -1                  2
Person ID: 8918ed0b-45fa-4740-85ae-d2bc60e5757b, index: 12
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15744      1        0  -1   -1   -1  -1                  2
14823      2        0  -1   -1   -1  -1                  2
17001      3        0  -1   -1   -1  -1                  2
Person ID: 985044fb-e2c2-40b1-9ae0-bb5b53f9a64a, index: 13
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16024      1        0  -1   -1   -1  -1                  2
15862      2        0  -1   -1   -1  -1                  2
16025      3        0  -1   -1   -1  -1                  2
16948      4        0  -1   -1   -1  -1                  2
Person ID: 9b7aa6e0-c793-432f-b3c4-62470e5ac709, index: 14
       visit  mci_sci  ad  ftd  als  pd  recruited_control
12183      1        0  -1   -1   -1  -1                  2
12184      2        0  -1   -1   -1  -1                  2
15613      3        0  -1   -1   -1  -1                  2
Person ID: a1619608-c250-4ecd-8f2c-ddbeb92995a6, index: 15
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16075      1        0  -1   -1   -1  -1                  2
16222      2        0  -1   -1   -1  -1                  2
16223      3        0  -1   -1   -1  -1                  2
Person ID: a56ee23b-e68a-46db-adc2-39d9921e4f5a, index: 16
       visit  mci_sci  ad  ftd  als  pd  recruited_control
13886      1        0  -1   -1   -1  -1                  2
13887      2        0  -1   -1   -1  -1                  2
13888      3        0  -1   -1   -1  -1                  2
Person ID: a5f15a51-2498-4358-b33d-0543c37409de, index: 17
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15819      1        0  -1   -1   -1  -1                  2
15993      2        0  -1   -1   -1  -1                  2
15994      3        0  -1   -1   -1  -1                  2
Person ID: ab20ebf7-50af-42e7-9e47-1db3b3dbce0c, index: 18
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15630      1        0  -1   -1   -1  -1                  2
15634      2        0  -1   -1   -1  -1                  2
15635      3        0  -1   -1   -1  -1                  2
Person ID: b9b9aed9-6719-4438-8b03-73e428da6d8b, index: 19
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16011      1        0  -1   -1   -1  -1                  2
16926      2        0  -1   -1   -1  -1                  2
16939      3        0  -1   -1   -1  -1                  2
Person ID: bbb1bcbd-5f21-4c4e-ad3c-676129407255, index: 20
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15746      1        0  -1   -1   -1  -1                  2
15731      2        0  -1   -1   -1  -1                  2
Person ID: c44de45d-d1a9-4b39-ad34-794bfc8c8d66, index: 21
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16359      1        0  -1   -1   -1  -1                  2
17413      2        0  -1   -1   -1  -1                  2
17452      3        0  -1   -1   -1  -1                  2
17414      4        0  -1   -1   -1  -1                  2
Person ID: ca93cbe0-b786-4405-a794-5b7796147548, index: 22
       visit  mci_sci  ad  ftd  als  pd  recruited_control
13808      1        0  -1   -1   -1  -1                  2
15084      2        0  -1   -1   -1  -1                  2
15371      3        0  -1   -1   -1  -1                  2
Person ID: cb00bdd0-76db-4d88-a9af-7701a4a2d13c, index: 23
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16660      1        0  -1   -1   -1  -1                  2
16236      2        0  -1   -1   -1  -1                  2
16237      3        0  -1   -1   -1  -1                  2
Person ID: d6614be1-ef69-4902-ad85-2af2178f2520, index: 24
       visit  mci_sci  ad  ftd  als  pd  recruited_control
17293      1        0  -1   -1   -1  -1                  2
16218      2        0  -1   -1   -1  -1                  2
16073      3        0  -1   -1   -1  -1                  2
Person ID: ec7748a6-d896-4631-87eb-9bea5ae6556f, index: 25
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15045      1        0  -1   -1   -1  -1                  2
15320      2        0  -1   -1   -1  -1                  2
Person ID: ed8aebf1-492d-4741-83e3-ac1b5c301789, index: 26
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15343      1        0  -1   -1   -1  -1                  2
15313      2        0  -1   -1   -1  -1                  2
16460      3        0  -1   -1   -1  -1                  2
Person ID: f731deaf-e8f8-490c-abff-e99e8c983cdd, index: 27
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15494      1        0  -1   -1   -1  -1                  2
15874      2        0  -1   -1   -1  -1                  2
16056      3        0  -1   -1   -1  -1                  2
Person ID: fedfba9c-85d9-48c8-b956-d9b9854cc9d8, index: 28
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16485      1        0  -1   -1   -1  -1                  2
15065      2        0  -1   -1   -1  -1                  2
16486      3        0  -1   -1   -1  -1                  2
15066      4        0  -1   -1   -1  -1                  2

In [57]:
p4 = list(cohort_p[(cohort_p["Converters"] == "Non-Converter") & (cohort_p["Status"] == "CI") ]["person_id"].unique())
len(p4)

40

In [60]:
stage_patients4 = []
for gender, pid in rlt[2]["mci"].items():
    stage_patients4.extend(pid)
len(stage_patients4)

25

In [69]:
inter4 = set(p4) & set(stage_patients4)
len(inter4)

25

In [75]:
addition4 = set(p4) - inter4
stage_data4 = plasmaSomaSummary
patient_level4 = stage_data4.groupby("person_id")
count = 0
for pid, pdf in patient_level4:
    if pid in addition4:
        count += 1
        print(f"Person ID: {pid}, index: {count}")
        print(converter_check(pdf))
        print(pdf[["visit", "mci_sci", "ad", "ftd", "als", "pd", "recruited_control"]].sort_values(by="visit"))

Person ID: 078768db-e696-477a-964c-8e80291d3a17, index: 1
cu
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16951      1        0  -1   -1   -1  -1                  2
15858      2        0  -1   -1   -1  -1                  2
Person ID: 36c995ac-16cf-4108-b94d-b66c83742432, index: 2
cu
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16915      1        0  -1   -1   -1  -1                  2
15989      2        0  -1   -1   -1  -1                  2
Person ID: 4a13057c-cec6-47af-b923-a5568e936121, index: 3
cu2mci
       visit  mci_sci  ad  ftd  als  pd  recruited_control
14518      1        0  -1   -1   -1  -1                  2
14521      2        1  -1   -1   -1  -1                  2
14817      3        0  -1   -1   -1  -1                  2
Person ID: 5b226e3f-bffd-4c12-ad52-0ca14b7723bb, index: 4
cu
       visit  mci_sci  ad  ftd  als  pd  recruited_control
17473      1        0  -1   -1   -1  -1                  2
16782      2        0  -1   -1   -1  -1                  2
Person ID: ab3eb53e-7a89-4a49-ac74-f1ed149e2fbf, index: 5
cu2mci
       visit  mci_sci  ad  ftd  als  pd  recruited_control
17299      1        0  -1   -1   -1  -1                  2
17300      2        1  -1   -1   -1  -1                  2
16080      3        1  -1   -1   -1  -1                  2
Person ID: b9b9aed9-6719-4438-8b03-73e428da6d8b, index: 6
cu
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16011      1        0  -1   -1   -1  -1                  2
16926      2        0  -1   -1   -1  -1                  2
16939      3        0  -1   -1   -1  -1                  2
Person ID: bbb1bcbd-5f21-4c4e-ad3c-676129407255, index: 7
cu
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15746      1        0  -1   -1   -1  -1                  2
15731      2        0  -1   -1   -1  -1                  2
Person ID: cb00bdd0-76db-4d88-a9af-7701a4a2d13c, index: 8
cu
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16660      1        0  -1   -1   -1  -1                  2
16236      2        0  -1   -1   -1  -1                  2
16237      3        0  -1   -1   -1  -1                  2
Person ID: cd7f2292-a2bf-4087-a378-1bda40488315, index: 9
cu2mci
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16017      1        0  -1   -1   -1  -1                  2
15442      2        1  -1   -1   -1  -1                  2
Person ID: d6614be1-ef69-4902-ad85-2af2178f2520, index: 10
cu
       visit  mci_sci  ad  ftd  als  pd  recruited_control
17293      1        0  -1   -1   -1  -1                  2
16218      2        0  -1   -1   -1  -1                  2
16073      3        0  -1   -1   -1  -1                  2
Person ID: ed38723a-d3f9-4447-bdd8-b320237f6644, index: 11
cu2mci
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15338      1        0  -1   -1   -1  -1                  2
15061      2        1  -1   -1   -1  -1                  2
16491      3        1  -1   -1   -1  -1                  2
15062      4        1  -1   -1   -1  -1                  2
13866      5        0  -1   -1   -1  -1                  2
Person ID: efb857e8-7e04-4f97-8cb4-f5d76c571ae1, index: 12
cu2mci
       visit  mci_sci  ad  ftd  als  pd  recruited_control
17288      1        0  -1   -1   -1  -1                  2
16646      2        1  -1   -1   -1  -1                  2
17286      3        1  -1   -1   -1  -1                  2
Person ID: f1bbdf85-17ee-4e37-aabe-d2fa17187e05, index: 13
cu2mci
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16019      1        0  -1   -1   -1  -1                  2
16935      2        1  -1   -1   -1  -1                  2
15837      3        0  -1   -1   -1  -1                  2
15441      4        1  -1   -1   -1  -1                  2
16936      5        1  -1   -1   -1  -1                  2
Person ID: fd63a060-040d-4583-bdf6-3934ac3bf063, index: 14
cu2mci
       visit  mci_sci  ad  ftd  als  pd  recruited_control
15304      1        0  -1   -1   -1  -1                  2
16425      2        1  -1   -1   -1  -1                  2
15021      3        1  -1   -1   -1  -1                  2
Person ID: fedfba9c-85d9-48c8-b956-d9b9854cc9d8, index: 15
cu
       visit  mci_sci  ad  ftd  als  pd  recruited_control
16485      1        0  -1   -1   -1  -1                  2
15065      2        0  -1   -1   -1  -1                  2
16486      3        0  -1   -1   -1  -1                  2
15066      4        0  -1   -1   -1  -1                  2

In [31]:
cohort_p["Status"].unique()

array(['CU', 'CI'], dtype=object)

In [32]:
cohort_p["Diagnosis"].unique()

array(['CU', 'MCI/SCI', 'Other'], dtype=object)

In [33]:
cohort_p["Progression_Simple"].unique()

array(['CU', 'MCI/SCI → Other', 'CU → MCI/SCI', 'Other', 'CU → Other',
       'MCI/SCI', 'CU → MCI/SCI → Other', 'Other → MCI/SCI → Other',
       'MCI/SCI → Other → MCI/SCI', 'Other → MCI/SCI',
       'Other → MCI/SCI → Other → MCI/SCI'], dtype=object)